<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Text\TopOccurrences;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations.Aggregation.Text.TopOccurrences.TopOccurrence</code>
 */
class TopOccurrence extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string value = 1;</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>int64 occurs = 2;</code>
     */
    protected $occurs = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $value
     *     @type int|string $occurs
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 occurs = 2;</code>
     * @return int|string
     */
    public function getOccurs()
    {
        return $this->occurs;
    }

    /**
     * Generated from protobuf field <code>int64 occurs = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOccurs(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->occurs = $var;

        return $this;
    }

}

