<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateRequest\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateRequest.Aggregation.Boolean</code>
 */
class Boolean extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     */
    protected $count = false;
    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     */
    protected $type = false;
    /**
     * Generated from protobuf field <code>bool total_true = 3;</code>
     */
    protected $total_true = false;
    /**
     * Generated from protobuf field <code>bool total_false = 4;</code>
     */
    protected $total_false = false;
    /**
     * Generated from protobuf field <code>bool percentage_true = 5;</code>
     */
    protected $percentage_true = false;
    /**
     * Generated from protobuf field <code>bool percentage_false = 6;</code>
     */
    protected $percentage_false = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $count
     *     @type bool $type
     *     @type bool $total_true
     *     @type bool $total_false
     *     @type bool $percentage_true
     *     @type bool $percentage_false
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @return bool
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCount(bool $var)
    {
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @return bool
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setType(bool $var)
    {
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool total_true = 3;</code>
     * @return bool
     */
    public function getTotalTrue()
    {
        return $this->total_true;
    }

    /**
     * Generated from protobuf field <code>bool total_true = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTotalTrue(bool $var)
    {
        $this->total_true = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool total_false = 4;</code>
     * @return bool
     */
    public function getTotalFalse()
    {
        return $this->total_false;
    }

    /**
     * Generated from protobuf field <code>bool total_false = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setTotalFalse(bool $var)
    {
        $this->total_false = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool percentage_true = 5;</code>
     * @return bool
     */
    public function getPercentageTrue()
    {
        return $this->percentage_true;
    }

    /**
     * Generated from protobuf field <code>bool percentage_true = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setPercentageTrue(bool $var)
    {
        $this->percentage_true = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool percentage_false = 6;</code>
     * @return bool
     */
    public function getPercentageFalse()
    {
        return $this->percentage_false;
    }

    /**
     * Generated from protobuf field <code>bool percentage_false = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setPercentageFalse(bool $var)
    {
        $this->percentage_false = $var;

        return $this;
    }

}

