<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateRequest\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateRequest.Aggregation.Date</code>
 */
class Date extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     */
    protected $count = false;
    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     */
    protected $type = false;
    /**
     * Generated from protobuf field <code>bool median = 3;</code>
     */
    protected $median = false;
    /**
     * Generated from protobuf field <code>bool mode = 4;</code>
     */
    protected $mode = false;
    /**
     * Generated from protobuf field <code>bool maximum = 5;</code>
     */
    protected $maximum = false;
    /**
     * Generated from protobuf field <code>bool minimum = 6;</code>
     */
    protected $minimum = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $count
     *     @type bool $type
     *     @type bool $median
     *     @type bool $mode
     *     @type bool $maximum
     *     @type bool $minimum
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @return bool
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCount(bool $var)
    {
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @return bool
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setType(bool $var)
    {
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool median = 3;</code>
     * @return bool
     */
    public function getMedian()
    {
        return $this->median;
    }

    /**
     * Generated from protobuf field <code>bool median = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setMedian(bool $var)
    {
        $this->median = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool mode = 4;</code>
     * @return bool
     */
    public function getMode()
    {
        return $this->mode;
    }

    /**
     * Generated from protobuf field <code>bool mode = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setMode(bool $var)
    {
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool maximum = 5;</code>
     * @return bool
     */
    public function getMaximum()
    {
        return $this->maximum;
    }

    /**
     * Generated from protobuf field <code>bool maximum = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setMaximum(bool $var)
    {
        $this->maximum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool minimum = 6;</code>
     * @return bool
     */
    public function getMinimum()
    {
        return $this->minimum;
    }

    /**
     * Generated from protobuf field <code>bool minimum = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setMinimum(bool $var)
    {
        $this->minimum = $var;

        return $this;
    }

}

