<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateRequest\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateRequest.Aggregation.Text</code>
 */
class Text extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     */
    protected $count = false;
    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     */
    protected $type = false;
    /**
     * Generated from protobuf field <code>bool top_occurences = 3;</code>
     */
    protected $top_occurences = false;
    /**
     * Generated from protobuf field <code>optional uint32 top_occurences_limit = 4;</code>
     */
    protected $top_occurences_limit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $count
     *     @type bool $type
     *     @type bool $top_occurences
     *     @type int $top_occurences_limit
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @return bool
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * Generated from protobuf field <code>bool count = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setCount(bool $var)
    {
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @return bool
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>bool type = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setType(bool $var)
    {
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool top_occurences = 3;</code>
     * @return bool
     */
    public function getTopOccurences()
    {
        return $this->top_occurences;
    }

    /**
     * Generated from protobuf field <code>bool top_occurences = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setTopOccurences(bool $var)
    {
        $this->top_occurences = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 top_occurences_limit = 4;</code>
     * @return int
     */
    public function getTopOccurencesLimit()
    {
        return isset($this->top_occurences_limit) ? $this->top_occurences_limit : 0;
    }

    public function hasTopOccurencesLimit()
    {
        return isset($this->top_occurences_limit);
    }

    public function clearTopOccurencesLimit()
    {
        unset($this->top_occurences_limit);
    }

    /**
     * Generated from protobuf field <code>optional uint32 top_occurences_limit = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTopOccurencesLimit(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->top_occurences_limit = $var;

        return $this;
    }

}

