<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeCohereMetadata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeCohereMetadata.Tokens</code>
 */
class Tokens extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional double input_tokens = 1;</code>
     */
    protected $input_tokens = null;
    /**
     * Generated from protobuf field <code>optional double output_tokens = 2;</code>
     */
    protected $output_tokens = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $input_tokens
     *     @type float $output_tokens
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional double input_tokens = 1;</code>
     * @return float
     */
    public function getInputTokens()
    {
        return isset($this->input_tokens) ? $this->input_tokens : 0.0;
    }

    public function hasInputTokens()
    {
        return isset($this->input_tokens);
    }

    public function clearInputTokens()
    {
        unset($this->input_tokens);
    }

    /**
     * Generated from protobuf field <code>optional double input_tokens = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setInputTokens(float $var)
    {
        $this->input_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double output_tokens = 2;</code>
     * @return float
     */
    public function getOutputTokens()
    {
        return isset($this->output_tokens) ? $this->output_tokens : 0.0;
    }

    public function hasOutputTokens()
    {
        return isset($this->output_tokens);
    }

    public function clearOutputTokens()
    {
        unset($this->output_tokens);
    }

    /**
     * Generated from protobuf field <code>optional double output_tokens = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setOutputTokens(float $var)
    {
        $this->output_tokens = $var;

        return $this;
    }

}

