<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1\BatchObject;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchObject.SingleTargetRefProps</code>
 */
class SingleTargetRefProps extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string uuids = 1;</code>
     */
    private $uuids;
    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     */
    protected $prop_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $uuids
     *     @type string $prop_name
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string uuids = 1;</code>
     * @return RepeatedField<string>
     */
    public function getUuids()
    {
        return $this->uuids;
    }

    /**
     * Generated from protobuf field <code>repeated string uuids = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setUuids(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->uuids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @return string
     */
    public function getPropName()
    {
        return $this->prop_name;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPropName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prop_name = $var;

        return $this;
    }

}

