<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1\BatchStreamRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchStreamRequest.Data</code>
 */
class Data extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.Objects objects = 1;</code>
     */
    protected $objects = null;
    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.References references = 2;</code>
     */
    protected $references = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\Objects $objects
     *     @type \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\References $references
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.Objects objects = 1;</code>
     * @return \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\Objects|null
     */
    public function getObjects()
    {
        return $this->objects;
    }

    public function hasObjects()
    {
        return isset($this->objects);
    }

    public function clearObjects()
    {
        unset($this->objects);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.Objects objects = 1;</code>
     * @param \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\Objects $var
     * @return $this
     */
    public function setObjects(\Weaviate\Client\Proto\V1\BatchStreamRequest\Data\Objects|null $var)
    {
        $this->objects = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.References references = 2;</code>
     * @return \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\References|null
     */
    public function getReferences()
    {
        return $this->references;
    }

    public function hasReferences()
    {
        return isset($this->references);
    }

    public function clearReferences()
    {
        unset($this->references);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data.References references = 2;</code>
     * @param \Weaviate\Client\Proto\V1\BatchStreamRequest\Data\References $var
     * @return $this
     */
    public function setReferences(\Weaviate\Client\Proto\V1\BatchStreamRequest\Data\References|null $var)
    {
        $this->references = $var;

        return $this;
    }

}

