<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1\BatchStreamRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchStreamRequest.Start</code>
 */
class Start extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 1;</code>
     */
    protected $consistency_level = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $consistency_level
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 1;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\ConsistencyLevel}
     */
    public function getConsistencyLevel()
    {
        return isset($this->consistency_level) ? $this->consistency_level : 0;
    }

    public function hasConsistencyLevel()
    {
        return isset($this->consistency_level);
    }

    public function clearConsistencyLevel()
    {
        unset($this->consistency_level);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 1;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\ConsistencyLevel}
     * @return $this
     */
    public function setConsistencyLevel(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

}

