<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1\Hybrid;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.Hybrid.FusionType</code>
 */
class FusionType
{
    /**
     * Generated from protobuf enum <code>FUSION_TYPE_UNSPECIFIED = 0;</code>
     */
    const FUSION_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>FUSION_TYPE_RANKED = 1;</code>
     */
    const FUSION_TYPE_RANKED = 1;
    /**
     * Generated from protobuf enum <code>FUSION_TYPE_RELATIVE_SCORE = 2;</code>
     */
    const FUSION_TYPE_RELATIVE_SCORE = 2;

    private static $valueToName = [
        self::FUSION_TYPE_UNSPECIFIED => 'FUSION_TYPE_UNSPECIFIED',
        self::FUSION_TYPE_RANKED => 'FUSION_TYPE_RANKED',
        self::FUSION_TYPE_RELATIVE_SCORE => 'FUSION_TYPE_RELATIVE_SCORE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

