<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1\Vectors;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.Vectors.VectorType</code>
 */
class VectorType
{
    /**
     * Generated from protobuf enum <code>VECTOR_TYPE_UNSPECIFIED = 0;</code>
     */
    const VECTOR_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>VECTOR_TYPE_SINGLE_FP32 = 1;</code>
     */
    const VECTOR_TYPE_SINGLE_FP32 = 1;
    /**
     * Generated from protobuf enum <code>VECTOR_TYPE_MULTI_FP32 = 2;</code>
     */
    const VECTOR_TYPE_MULTI_FP32 = 2;

    private static $valueToName = [
        self::VECTOR_TYPE_UNSPECIFIED => 'VECTOR_TYPE_UNSPECIFIED',
        self::VECTOR_TYPE_SINGLE_FP32 => 'VECTOR_TYPE_SINGLE_FP32',
        self::VECTOR_TYPE_MULTI_FP32 => 'VECTOR_TYPE_MULTI_FP32',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

