<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeOpenAI;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.GenerativeOpenAI.Verbosity</code>
 */
class Verbosity
{
    /**
     * Generated from protobuf enum <code>VERBOSITY_UNSPECIFIED = 0;</code>
     */
    const VERBOSITY_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>VERBOSITY_LOW = 1;</code>
     */
    const VERBOSITY_LOW = 1;
    /**
     * Generated from protobuf enum <code>VERBOSITY_MEDIUM = 2;</code>
     */
    const VERBOSITY_MEDIUM = 2;
    /**
     * Generated from protobuf enum <code>VERBOSITY_HIGH = 3;</code>
     */
    const VERBOSITY_HIGH = 3;

    private static $valueToName = [
        self::VERBOSITY_UNSPECIFIED => 'VERBOSITY_UNSPECIFIED',
        self::VERBOSITY_LOW => 'VERBOSITY_LOW',
        self::VERBOSITY_MEDIUM => 'VERBOSITY_MEDIUM',
        self::VERBOSITY_HIGH => 'VERBOSITY_HIGH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

