<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeSearch;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeSearch.Grouped</code>
 */
class Grouped extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string task = 1;</code>
     */
    protected $task = '';
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray properties = 2;</code>
     */
    protected $properties = null;
    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     */
    private $queries;
    /**
     * Generated from protobuf field <code>bool debug = 4;</code>
     */
    protected $debug = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $task
     *     @type \Weaviate\Client\Proto\V1\TextArray $properties
     *     @type \Weaviate\Client\Proto\V1\GenerativeProvider[] $queries
     *           only allow one at the beginning, but multiple in the future
     *     @type bool $debug
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string task = 1;</code>
     * @return string
     */
    public function getTask()
    {
        return $this->task;
    }

    /**
     * Generated from protobuf field <code>string task = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTask(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->task = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray properties = 2;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray properties = 2;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setProperties(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->properties = $var;

        return $this;
    }

    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\GenerativeProvider>
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeProvider[] $var
     * @return $this
     */
    public function setQueries(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\GenerativeProvider::class);
        $this->queries = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool debug = 4;</code>
     * @return bool
     */
    public function getDebug()
    {
        return $this->debug;
    }

    /**
     * Generated from protobuf field <code>bool debug = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDebug(bool $var)
    {
        $this->debug = $var;

        return $this;
    }

}

