<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeSearch;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeSearch.Single</code>
 */
class Single extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string prompt = 1;</code>
     */
    protected $prompt = '';
    /**
     * Generated from protobuf field <code>bool debug = 2;</code>
     */
    protected $debug = false;
    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     */
    private $queries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $prompt
     *     @type bool $debug
     *     @type \Weaviate\Client\Proto\V1\GenerativeProvider[] $queries
     *           only allow one at the beginning, but multiple in the future
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string prompt = 1;</code>
     * @return string
     */
    public function getPrompt()
    {
        return $this->prompt;
    }

    /**
     * Generated from protobuf field <code>string prompt = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrompt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prompt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool debug = 2;</code>
     * @return bool
     */
    public function getDebug()
    {
        return $this->debug;
    }

    /**
     * Generated from protobuf field <code>bool debug = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setDebug(bool $var)
    {
        $this->debug = $var;

        return $this;
    }

    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\GenerativeProvider>
     */
    public function getQueries()
    {
        return $this->queries;
    }

    /**
     * only allow one at the beginning, but multiple in the future
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.GenerativeProvider queries = 3;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeProvider[] $var
     * @return $this
     */
    public function setQueries(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\GenerativeProvider::class);
        $this->queries = $arr;

        return $this;
    }

}

