<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1\Boost;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Boost.Condition</code>
 */
class Condition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional float weight = 5;</code>
     */
    protected $weight = null;
    protected $condition;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\Filters $filter
     *     @type \Weaviate\Client\Proto\V1\Boost\TimeDecayFunction $time_decay
     *     @type \Weaviate\Client\Proto\V1\Boost\PropertyValueFunction $property_value
     *     @type \Weaviate\Client\Proto\V1\Boost\NumericDecayFunction $numeric_decay
     *     @type float $weight
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters filter = 1;</code>
     * @return \Weaviate\Client\Proto\V1\Filters|null
     */
    public function getFilter()
    {
        return $this->readOneof(1);
    }

    public function hasFilter()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters filter = 1;</code>
     * @param \Weaviate\Client\Proto\V1\Filters $var
     * @return $this
     */
    public function setFilter(\Weaviate\Client\Proto\V1\Filters|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.TimeDecayFunction time_decay = 2;</code>
     * @return \Weaviate\Client\Proto\V1\Boost\TimeDecayFunction|null
     */
    public function getTimeDecay()
    {
        return $this->readOneof(2);
    }

    public function hasTimeDecay()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.TimeDecayFunction time_decay = 2;</code>
     * @param \Weaviate\Client\Proto\V1\Boost\TimeDecayFunction $var
     * @return $this
     */
    public function setTimeDecay(\Weaviate\Client\Proto\V1\Boost\TimeDecayFunction|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.PropertyValueFunction property_value = 3;</code>
     * @return \Weaviate\Client\Proto\V1\Boost\PropertyValueFunction|null
     */
    public function getPropertyValue()
    {
        return $this->readOneof(3);
    }

    public function hasPropertyValue()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.PropertyValueFunction property_value = 3;</code>
     * @param \Weaviate\Client\Proto\V1\Boost\PropertyValueFunction $var
     * @return $this
     */
    public function setPropertyValue(\Weaviate\Client\Proto\V1\Boost\PropertyValueFunction|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.NumericDecayFunction numeric_decay = 4;</code>
     * @return \Weaviate\Client\Proto\V1\Boost\NumericDecayFunction|null
     */
    public function getNumericDecay()
    {
        return $this->readOneof(4);
    }

    public function hasNumericDecay()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Boost.NumericDecayFunction numeric_decay = 4;</code>
     * @param \Weaviate\Client\Proto\V1\Boost\NumericDecayFunction $var
     * @return $this
     */
    public function setNumericDecay(\Weaviate\Client\Proto\V1\Boost\NumericDecayFunction|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 5;</code>
     * @return float
     */
    public function getWeight()
    {
        return isset($this->weight) ? $this->weight : 0.0;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * Generated from protobuf field <code>optional float weight = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight(float $var)
    {
        $this->weight = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getCondition()
    {
        return $this->whichOneof("condition");
    }

}

