<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1\Boost;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.Boost.DecayCurve</code>
 */
class DecayCurve
{
    /**
     * Generated from protobuf enum <code>DECAY_CURVE_UNSPECIFIED = 0;</code>
     */
    const DECAY_CURVE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>DECAY_CURVE_GAUSS = 1;</code>
     */
    const DECAY_CURVE_GAUSS = 1;
    /**
     * Generated from protobuf enum <code>DECAY_CURVE_LINEAR = 2;</code>
     */
    const DECAY_CURVE_LINEAR = 2;
    /**
     * Generated from protobuf enum <code>DECAY_CURVE_EXPONENTIAL = 3;</code>
     */
    const DECAY_CURVE_EXPONENTIAL = 3;

    private static $valueToName = [
        self::DECAY_CURVE_UNSPECIFIED => 'DECAY_CURVE_UNSPECIFIED',
        self::DECAY_CURVE_GAUSS => 'DECAY_CURVE_GAUSS',
        self::DECAY_CURVE_LINEAR => 'DECAY_CURVE_LINEAR',
        self::DECAY_CURVE_EXPONENTIAL => 'DECAY_CURVE_EXPONENTIAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

