<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1\Boost;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Boost.PropertyValueFunction</code>
 */
class PropertyValueFunction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string property = 1;</code>
     */
    protected $property = '';
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Boost.PropertyValueModifier modifier = 2;</code>
     */
    protected $modifier = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $property
     *     @type int $modifier
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @return string
     */
    public function getProperty()
    {
        return $this->property;
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProperty(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->property = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Boost.PropertyValueModifier modifier = 2;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\Boost\PropertyValueModifier}
     */
    public function getModifier()
    {
        return isset($this->modifier) ? $this->modifier : 0;
    }

    public function hasModifier()
    {
        return isset($this->modifier);
    }

    public function clearModifier()
    {
        unset($this->modifier);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Boost.PropertyValueModifier modifier = 2;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\Boost\PropertyValueModifier}
     * @return $this
     */
    public function setModifier(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\Boost\PropertyValueModifier::class);
        $this->modifier = $var;

        return $this;
    }

}

