<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations.Aggregation.Boolean</code>
 */
class Boolean extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     */
    protected $count = null;
    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional int64 total_true = 3;</code>
     */
    protected $total_true = null;
    /**
     * Generated from protobuf field <code>optional int64 total_false = 4;</code>
     */
    protected $total_false = null;
    /**
     * Generated from protobuf field <code>optional double percentage_true = 5;</code>
     */
    protected $percentage_true = null;
    /**
     * Generated from protobuf field <code>optional double percentage_false = 6;</code>
     */
    protected $percentage_false = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $count
     *     @type string $type
     *     @type int|string $total_true
     *     @type int|string $total_false
     *     @type float $percentage_true
     *     @type float $percentage_false
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @return int|string
     */
    public function getCount()
    {
        return isset($this->count) ? $this->count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasCount()
    {
        return isset($this->count);
    }

    public function clearCount()
    {
        unset($this->count);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 total_true = 3;</code>
     * @return int|string
     */
    public function getTotalTrue()
    {
        return isset($this->total_true) ? $this->total_true : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasTotalTrue()
    {
        return isset($this->total_true);
    }

    public function clearTotalTrue()
    {
        unset($this->total_true);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_true = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalTrue(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->total_true = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 total_false = 4;</code>
     * @return int|string
     */
    public function getTotalFalse()
    {
        return isset($this->total_false) ? $this->total_false : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasTotalFalse()
    {
        return isset($this->total_false);
    }

    public function clearTotalFalse()
    {
        unset($this->total_false);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_false = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalFalse(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->total_false = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double percentage_true = 5;</code>
     * @return float
     */
    public function getPercentageTrue()
    {
        return isset($this->percentage_true) ? $this->percentage_true : 0.0;
    }

    public function hasPercentageTrue()
    {
        return isset($this->percentage_true);
    }

    public function clearPercentageTrue()
    {
        unset($this->percentage_true);
    }

    /**
     * Generated from protobuf field <code>optional double percentage_true = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentageTrue(float $var)
    {
        $this->percentage_true = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double percentage_false = 6;</code>
     * @return float
     */
    public function getPercentageFalse()
    {
        return isset($this->percentage_false) ? $this->percentage_false : 0.0;
    }

    public function hasPercentageFalse()
    {
        return isset($this->percentage_false);
    }

    public function clearPercentageFalse()
    {
        unset($this->percentage_false);
    }

    /**
     * Generated from protobuf field <code>optional double percentage_false = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPercentageFalse(float $var)
    {
        $this->percentage_false = $var;

        return $this;
    }

}

