<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations.Aggregation.Date</code>
 */
class Date extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     */
    protected $count = null;
    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional string median = 3;</code>
     */
    protected $median = null;
    /**
     * Generated from protobuf field <code>optional string mode = 4;</code>
     */
    protected $mode = null;
    /**
     * Generated from protobuf field <code>optional string maximum = 5;</code>
     */
    protected $maximum = null;
    /**
     * Generated from protobuf field <code>optional string minimum = 6;</code>
     */
    protected $minimum = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $count
     *     @type string $type
     *     @type string $median
     *     @type string $mode
     *     @type string $maximum
     *     @type string $minimum
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @return int|string
     */
    public function getCount()
    {
        return isset($this->count) ? $this->count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasCount()
    {
        return isset($this->count);
    }

    public function clearCount()
    {
        unset($this->count);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string median = 3;</code>
     * @return string
     */
    public function getMedian()
    {
        return isset($this->median) ? $this->median : '';
    }

    public function hasMedian()
    {
        return isset($this->median);
    }

    public function clearMedian()
    {
        unset($this->median);
    }

    /**
     * Generated from protobuf field <code>optional string median = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMedian(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->median = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string mode = 4;</code>
     * @return string
     */
    public function getMode()
    {
        return isset($this->mode) ? $this->mode : '';
    }

    public function hasMode()
    {
        return isset($this->mode);
    }

    public function clearMode()
    {
        unset($this->mode);
    }

    /**
     * Generated from protobuf field <code>optional string mode = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string maximum = 5;</code>
     * @return string
     */
    public function getMaximum()
    {
        return isset($this->maximum) ? $this->maximum : '';
    }

    public function hasMaximum()
    {
        return isset($this->maximum);
    }

    public function clearMaximum()
    {
        unset($this->maximum);
    }

    /**
     * Generated from protobuf field <code>optional string maximum = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMaximum(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->maximum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string minimum = 6;</code>
     * @return string
     */
    public function getMinimum()
    {
        return isset($this->minimum) ? $this->minimum : '';
    }

    public function hasMinimum()
    {
        return isset($this->minimum);
    }

    public function clearMinimum()
    {
        unset($this->minimum);
    }

    /**
     * Generated from protobuf field <code>optional string minimum = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMinimum(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->minimum = $var;

        return $this;
    }

}

