<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations.Aggregation.Number</code>
 */
class Number extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     */
    protected $count = null;
    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional double mean = 3;</code>
     */
    protected $mean = null;
    /**
     * Generated from protobuf field <code>optional double median = 4;</code>
     */
    protected $median = null;
    /**
     * Generated from protobuf field <code>optional double mode = 5;</code>
     */
    protected $mode = null;
    /**
     * Generated from protobuf field <code>optional double maximum = 6;</code>
     */
    protected $maximum = null;
    /**
     * Generated from protobuf field <code>optional double minimum = 7;</code>
     */
    protected $minimum = null;
    /**
     * Generated from protobuf field <code>optional double sum = 8;</code>
     */
    protected $sum = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $count
     *     @type string $type
     *     @type float $mean
     *     @type float $median
     *     @type float $mode
     *     @type float $maximum
     *     @type float $minimum
     *     @type float $sum
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @return int|string
     */
    public function getCount()
    {
        return isset($this->count) ? $this->count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasCount()
    {
        return isset($this->count);
    }

    public function clearCount()
    {
        unset($this->count);
    }

    /**
     * Generated from protobuf field <code>optional int64 count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional string type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setType(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double mean = 3;</code>
     * @return float
     */
    public function getMean()
    {
        return isset($this->mean) ? $this->mean : 0.0;
    }

    public function hasMean()
    {
        return isset($this->mean);
    }

    public function clearMean()
    {
        unset($this->mean);
    }

    /**
     * Generated from protobuf field <code>optional double mean = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMean(float $var)
    {
        $this->mean = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double median = 4;</code>
     * @return float
     */
    public function getMedian()
    {
        return isset($this->median) ? $this->median : 0.0;
    }

    public function hasMedian()
    {
        return isset($this->median);
    }

    public function clearMedian()
    {
        unset($this->median);
    }

    /**
     * Generated from protobuf field <code>optional double median = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setMedian(float $var)
    {
        $this->median = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double mode = 5;</code>
     * @return float
     */
    public function getMode()
    {
        return isset($this->mode) ? $this->mode : 0.0;
    }

    public function hasMode()
    {
        return isset($this->mode);
    }

    public function clearMode()
    {
        unset($this->mode);
    }

    /**
     * Generated from protobuf field <code>optional double mode = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setMode(float $var)
    {
        $this->mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double maximum = 6;</code>
     * @return float
     */
    public function getMaximum()
    {
        return isset($this->maximum) ? $this->maximum : 0.0;
    }

    public function hasMaximum()
    {
        return isset($this->maximum);
    }

    public function clearMaximum()
    {
        unset($this->maximum);
    }

    /**
     * Generated from protobuf field <code>optional double maximum = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setMaximum(float $var)
    {
        $this->maximum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double minimum = 7;</code>
     * @return float
     */
    public function getMinimum()
    {
        return isset($this->minimum) ? $this->minimum : 0.0;
    }

    public function hasMinimum()
    {
        return isset($this->minimum);
    }

    public function clearMinimum()
    {
        unset($this->minimum);
    }

    /**
     * Generated from protobuf field <code>optional double minimum = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setMinimum(float $var)
    {
        $this->minimum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double sum = 8;</code>
     * @return float
     */
    public function getSum()
    {
        return isset($this->sum) ? $this->sum : 0.0;
    }

    public function hasSum()
    {
        return isset($this->sum);
    }

    public function clearSum()
    {
        unset($this->sum);
    }

    /**
     * Generated from protobuf field <code>optional double sum = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setSum(float $var)
    {
        $this->sum = $var;

        return $this;
    }

}

