<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeAnthropicMetadata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeAnthropicMetadata.Usage</code>
 */
class Usage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 input_tokens = 1;</code>
     */
    protected $input_tokens = 0;
    /**
     * Generated from protobuf field <code>int64 output_tokens = 2;</code>
     */
    protected $output_tokens = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $input_tokens
     *     @type int|string $output_tokens
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 input_tokens = 1;</code>
     * @return int|string
     */
    public function getInputTokens()
    {
        return $this->input_tokens;
    }

    /**
     * Generated from protobuf field <code>int64 input_tokens = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInputTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->input_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 output_tokens = 2;</code>
     * @return int|string
     */
    public function getOutputTokens()
    {
        return $this->output_tokens;
    }

    /**
     * Generated from protobuf field <code>int64 output_tokens = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOutputTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->output_tokens = $var;

        return $this;
    }

}

