<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1\SearchOperatorOptions;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.SearchOperatorOptions.Operator</code>
 */
class Operator
{
    /**
     * Generated from protobuf enum <code>OPERATOR_UNSPECIFIED = 0;</code>
     */
    const OPERATOR_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OPERATOR_OR = 1;</code>
     */
    const OPERATOR_OR = 1;
    /**
     * Generated from protobuf enum <code>OPERATOR_AND = 2;</code>
     */
    const OPERATOR_AND = 2;
    /**
     * Fails unless every searched property shares the same tokenization and analyzer settings.
     *
     * Generated from protobuf enum <code>OPERATOR_AND_CROSS = 3;</code>
     */
    const OPERATOR_AND_CROSS = 3;

    private static $valueToName = [
        self::OPERATOR_UNSPECIFIED => 'OPERATOR_UNSPECIFIED',
        self::OPERATOR_OR => 'OPERATOR_OR',
        self::OPERATOR_AND => 'OPERATOR_AND',
        self::OPERATOR_AND_CROSS => 'OPERATOR_AND_CROSS',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

