<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1\Filters;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.Filters.Operator</code>
 */
class Operator
{
    /**
     * Generated from protobuf enum <code>OPERATOR_UNSPECIFIED = 0;</code>
     */
    const OPERATOR_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>OPERATOR_EQUAL = 1;</code>
     */
    const OPERATOR_EQUAL = 1;
    /**
     * Generated from protobuf enum <code>OPERATOR_NOT_EQUAL = 2;</code>
     */
    const OPERATOR_NOT_EQUAL = 2;
    /**
     * Generated from protobuf enum <code>OPERATOR_GREATER_THAN = 3;</code>
     */
    const OPERATOR_GREATER_THAN = 3;
    /**
     * Generated from protobuf enum <code>OPERATOR_GREATER_THAN_EQUAL = 4;</code>
     */
    const OPERATOR_GREATER_THAN_EQUAL = 4;
    /**
     * Generated from protobuf enum <code>OPERATOR_LESS_THAN = 5;</code>
     */
    const OPERATOR_LESS_THAN = 5;
    /**
     * Generated from protobuf enum <code>OPERATOR_LESS_THAN_EQUAL = 6;</code>
     */
    const OPERATOR_LESS_THAN_EQUAL = 6;
    /**
     * Generated from protobuf enum <code>OPERATOR_AND = 7;</code>
     */
    const OPERATOR_AND = 7;
    /**
     * Generated from protobuf enum <code>OPERATOR_OR = 8;</code>
     */
    const OPERATOR_OR = 8;
    /**
     * Generated from protobuf enum <code>OPERATOR_WITHIN_GEO_RANGE = 9;</code>
     */
    const OPERATOR_WITHIN_GEO_RANGE = 9;
    /**
     * Generated from protobuf enum <code>OPERATOR_LIKE = 10;</code>
     */
    const OPERATOR_LIKE = 10;
    /**
     * Generated from protobuf enum <code>OPERATOR_IS_NULL = 11;</code>
     */
    const OPERATOR_IS_NULL = 11;
    /**
     * Generated from protobuf enum <code>OPERATOR_CONTAINS_ANY = 12;</code>
     */
    const OPERATOR_CONTAINS_ANY = 12;
    /**
     * Generated from protobuf enum <code>OPERATOR_CONTAINS_ALL = 13;</code>
     */
    const OPERATOR_CONTAINS_ALL = 13;
    /**
     * Generated from protobuf enum <code>OPERATOR_CONTAINS_NONE = 14;</code>
     */
    const OPERATOR_CONTAINS_NONE = 14;
    /**
     * Generated from protobuf enum <code>OPERATOR_NOT = 15;</code>
     */
    const OPERATOR_NOT = 15;

    private static $valueToName = [
        self::OPERATOR_UNSPECIFIED => 'OPERATOR_UNSPECIFIED',
        self::OPERATOR_EQUAL => 'OPERATOR_EQUAL',
        self::OPERATOR_NOT_EQUAL => 'OPERATOR_NOT_EQUAL',
        self::OPERATOR_GREATER_THAN => 'OPERATOR_GREATER_THAN',
        self::OPERATOR_GREATER_THAN_EQUAL => 'OPERATOR_GREATER_THAN_EQUAL',
        self::OPERATOR_LESS_THAN => 'OPERATOR_LESS_THAN',
        self::OPERATOR_LESS_THAN_EQUAL => 'OPERATOR_LESS_THAN_EQUAL',
        self::OPERATOR_AND => 'OPERATOR_AND',
        self::OPERATOR_OR => 'OPERATOR_OR',
        self::OPERATOR_WITHIN_GEO_RANGE => 'OPERATOR_WITHIN_GEO_RANGE',
        self::OPERATOR_LIKE => 'OPERATOR_LIKE',
        self::OPERATOR_IS_NULL => 'OPERATOR_IS_NULL',
        self::OPERATOR_CONTAINS_ANY => 'OPERATOR_CONTAINS_ANY',
        self::OPERATOR_CONTAINS_ALL => 'OPERATOR_CONTAINS_ALL',
        self::OPERATOR_CONTAINS_NONE => 'OPERATOR_CONTAINS_NONE',
        self::OPERATOR_NOT => 'OPERATOR_NOT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

