<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1\Selection;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Selection.MMR</code>
 */
class MMR extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional uint32 limit = 1;</code>
     */
    protected $limit = null;
    /**
     * Generated from protobuf field <code>optional float balance = 2;</code>
     */
    protected $balance = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $limit
     *     @type float $balance
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional uint32 limit = 1;</code>
     * @return int
     */
    public function getLimit()
    {
        return isset($this->limit) ? $this->limit : 0;
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * Generated from protobuf field <code>optional uint32 limit = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float balance = 2;</code>
     * @return float
     */
    public function getBalance()
    {
        return isset($this->balance) ? $this->balance : 0.0;
    }

    public function hasBalance()
    {
        return isset($this->balance);
    }

    public function clearBalance()
    {
        unset($this->balance);
    }

    /**
     * Generated from protobuf field <code>optional float balance = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setBalance(float $var)
    {
        $this->balance = $var;

        return $this;
    }

}

