<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Group;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Group.GroupedBy</code>
 */
class GroupedBy extends \Google\Protobuf\Internal\Message
{
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     */
    private $path;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $path
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type string $text
     *     @type int|string $int
     *     @type bool $boolean
     *     @type float $number
     *     @type \Weaviate\Client\Proto\V1\TextArray $texts
     *     @type \Weaviate\Client\Proto\V1\IntArray $ints
     *     @type \Weaviate\Client\Proto\V1\BooleanArray $booleans
     *     @type \Weaviate\Client\Proto\V1\NumberArray $numbers
     *     @type \Weaviate\Client\Proto\V1\GeoCoordinatesFilter $geo
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     * @return RepeatedField<string>
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPath(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->path = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->readOneof(2);
    }

    public function hasText()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int = 3;</code>
     * @return int|string
     */
    public function getInt()
    {
        return $this->readOneof(3);
    }

    public function hasInt()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 int = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean = 4;</code>
     * @return bool
     */
    public function getBoolean()
    {
        return $this->readOneof(4);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>bool boolean = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolean(bool $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double number = 5;</code>
     * @return float
     */
    public function getNumber()
    {
        return $this->readOneof(5);
    }

    public function hasNumber()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>double number = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setNumber(float $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextArray texts = 6;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getTexts()
    {
        return $this->readOneof(6);
    }

    public function hasTexts()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextArray texts = 6;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setTexts(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntArray ints = 7;</code>
     * @return \Weaviate\Client\Proto\V1\IntArray|null
     */
    public function getInts()
    {
        return $this->readOneof(7);
    }

    public function hasInts()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntArray ints = 7;</code>
     * @param \Weaviate\Client\Proto\V1\IntArray $var
     * @return $this
     */
    public function setInts(\Weaviate\Client\Proto\V1\IntArray|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BooleanArray booleans = 8;</code>
     * @return \Weaviate\Client\Proto\V1\BooleanArray|null
     */
    public function getBooleans()
    {
        return $this->readOneof(8);
    }

    public function hasBooleans()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BooleanArray booleans = 8;</code>
     * @param \Weaviate\Client\Proto\V1\BooleanArray $var
     * @return $this
     */
    public function setBooleans(\Weaviate\Client\Proto\V1\BooleanArray|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberArray numbers = 9;</code>
     * @return \Weaviate\Client\Proto\V1\NumberArray|null
     */
    public function getNumbers()
    {
        return $this->readOneof(9);
    }

    public function hasNumbers()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberArray numbers = 9;</code>
     * @param \Weaviate\Client\Proto\V1\NumberArray $var
     * @return $this
     */
    public function setNumbers(\Weaviate\Client\Proto\V1\NumberArray|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinatesFilter geo = 10;</code>
     * @return \Weaviate\Client\Proto\V1\GeoCoordinatesFilter|null
     */
    public function getGeo()
    {
        return $this->readOneof(10);
    }

    public function hasGeo()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinatesFilter geo = 10;</code>
     * @param \Weaviate\Client\Proto\V1\GeoCoordinatesFilter $var
     * @return $this
     */
    public function setGeo(\Weaviate\Client\Proto\V1\GeoCoordinatesFilter|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

