<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply\Aggregations;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations.Aggregation</code>
 */
class Aggregation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string property = 1;</code>
     */
    protected $property = '';
    protected $aggregation;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $property
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Integer $int
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Number $number
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Text $text
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Boolean $boolean
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Date $date
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Reference $reference
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @return string
     */
    public function getProperty()
    {
        return $this->property;
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProperty(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->property = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Integer int = 2;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Integer|null
     */
    public function getInt()
    {
        return $this->readOneof(2);
    }

    public function hasInt()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Integer int = 2;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Integer $var
     * @return $this
     */
    public function setInt(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Integer|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Number number = 3;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Number|null
     */
    public function getNumber()
    {
        return $this->readOneof(3);
    }

    public function hasNumber()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Number number = 3;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Number $var
     * @return $this
     */
    public function setNumber(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Number|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Text text = 4;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Text|null
     */
    public function getText()
    {
        return $this->readOneof(4);
    }

    public function hasText()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Text text = 4;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Text $var
     * @return $this
     */
    public function setText(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Text|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Boolean boolean = 5;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Boolean|null
     */
    public function getBoolean()
    {
        return $this->readOneof(5);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Boolean boolean = 5;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Boolean $var
     * @return $this
     */
    public function setBoolean(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Boolean|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Date date = 6;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Date|null
     */
    public function getDate()
    {
        return $this->readOneof(6);
    }

    public function hasDate()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Date date = 6;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Date $var
     * @return $this
     */
    public function setDate(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Date|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Reference reference = 7;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Reference|null
     */
    public function getReference()
    {
        return $this->readOneof(7);
    }

    public function hasReference()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.AggregateReply.Aggregations.Aggregation.Reference reference = 7;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Reference $var
     * @return $this
     */
    public function setReference(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation\Reference|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getAggregation()
    {
        return $this->whichOneof("aggregation");
    }

}

