<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Aggregations</code>
 */
class Aggregations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateReply.Aggregations.Aggregation aggregations = 1;</code>
     */
    private $aggregations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation[] $aggregations
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateReply.Aggregations.Aggregation aggregations = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation>
     */
    public function getAggregations()
    {
        return $this->aggregations;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateReply.Aggregations.Aggregation aggregations = 1;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation[] $var
     * @return $this
     */
    public function setAggregations(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\AggregateReply\Aggregations\Aggregation::class);
        $this->aggregations = $arr;

        return $this;
    }

}

