<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1\AggregateReply;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateReply.Group</code>
 */
class Group extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 objects_count = 1;</code>
     */
    protected $objects_count = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Aggregations aggregations = 2;</code>
     */
    protected $aggregations = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Group.GroupedBy grouped_by = 3;</code>
     */
    protected $grouped_by = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $objects_count
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Aggregations $aggregations
     *     @type \Weaviate\Client\Proto\V1\AggregateReply\Group\GroupedBy $grouped_by
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 objects_count = 1;</code>
     * @return int|string
     */
    public function getObjectsCount()
    {
        return isset($this->objects_count) ? $this->objects_count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasObjectsCount()
    {
        return isset($this->objects_count);
    }

    public function clearObjectsCount()
    {
        unset($this->objects_count);
    }

    /**
     * Generated from protobuf field <code>optional int64 objects_count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setObjectsCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->objects_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Aggregations aggregations = 2;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Aggregations|null
     */
    public function getAggregations()
    {
        return $this->aggregations;
    }

    public function hasAggregations()
    {
        return isset($this->aggregations);
    }

    public function clearAggregations()
    {
        unset($this->aggregations);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Aggregations aggregations = 2;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Aggregations $var
     * @return $this
     */
    public function setAggregations(\Weaviate\Client\Proto\V1\AggregateReply\Aggregations|null $var)
    {
        $this->aggregations = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Group.GroupedBy grouped_by = 3;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateReply\Group\GroupedBy|null
     */
    public function getGroupedBy()
    {
        return $this->grouped_by;
    }

    public function hasGroupedBy()
    {
        return isset($this->grouped_by);
    }

    public function clearGroupedBy()
    {
        unset($this->grouped_by);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateReply.Group.GroupedBy grouped_by = 3;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateReply\Group\GroupedBy $var
     * @return $this
     */
    public function setGroupedBy(\Weaviate\Client\Proto\V1\AggregateReply\Group\GroupedBy|null $var)
    {
        $this->grouped_by = $var;

        return $this;
    }

}

