<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1\QueryProfile;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * SearchProfile holds the profiling details for a single search type within a shard.
 *
 * Generated from protobuf message <code>weaviate.v1.QueryProfile.SearchProfile</code>
 */
class SearchProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * details contains human-readable profiling metrics keyed by metric name.
     *
     * Generated from protobuf field <code>map<string, string> details = 1;</code>
     */
    private $details;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $details
     *           details contains human-readable profiling metrics keyed by metric name.
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * details contains human-readable profiling metrics keyed by metric name.
     *
     * Generated from protobuf field <code>map<string, string> details = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * details contains human-readable profiling metrics keyed by metric name.
     *
     * Generated from protobuf field <code>map<string, string> details = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setDetails(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->details = $arr;

        return $this;
    }

}

