<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1\QueryProfile;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ShardProfile holds profiling data for a single shard's contribution to a search query.
 *
 * Generated from protobuf message <code>weaviate.v1.QueryProfile.ShardProfile</code>
 */
class ShardProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * name is the identifier of the shard that was searched.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * node is the name of the cluster node that executed this shard search.
     *
     * Generated from protobuf field <code>string node = 2;</code>
     */
    protected $node = '';
    /**
     * searches maps search type (e.g., "vector", "keyword") to its profiling details.
     *
     * Generated from protobuf field <code>map<string, .weaviate.v1.QueryProfile.SearchProfile> searches = 3;</code>
     */
    private $searches;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           name is the identifier of the shard that was searched.
     *     @type string $node
     *           node is the name of the cluster node that executed this shard search.
     *     @type array|\Google\Protobuf\Internal\MapField $searches
     *           searches maps search type (e.g., "vector", "keyword") to its profiling details.
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * name is the identifier of the shard that was searched.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * name is the identifier of the shard that was searched.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * node is the name of the cluster node that executed this shard search.
     *
     * Generated from protobuf field <code>string node = 2;</code>
     * @return string
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * node is the name of the cluster node that executed this shard search.
     *
     * Generated from protobuf field <code>string node = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->node = $var;

        return $this;
    }

    /**
     * searches maps search type (e.g., "vector", "keyword") to its profiling details.
     *
     * Generated from protobuf field <code>map<string, .weaviate.v1.QueryProfile.SearchProfile> searches = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSearches()
    {
        return $this->searches;
    }

    /**
     * searches maps search type (e.g., "vector", "keyword") to its profiling details.
     *
     * Generated from protobuf field <code>map<string, .weaviate.v1.QueryProfile.SearchProfile> searches = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSearches(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\QueryProfile\SearchProfile::class);
        $this->searches = $arr;

        return $this;
    }

}

