<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.AggregateRequest</code>
 */
class AggregateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * required
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * parameters
     *
     * Generated from protobuf field <code>string tenant = 10;</code>
     */
    protected $tenant = '';
    /**
     * what is returned
     *
     * Generated from protobuf field <code>bool objects_count = 20;</code>
     */
    protected $objects_count = false;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateRequest.Aggregation aggregations = 21;</code>
     */
    private $aggregations;
    /**
     * affects aggregation results
     *
     * Generated from protobuf field <code>optional uint32 object_limit = 30;</code>
     */
    protected $object_limit = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateRequest.GroupBy group_by = 31;</code>
     */
    protected $group_by = null;
    /**
     * Generated from protobuf field <code>optional uint32 limit = 32;</code>
     */
    protected $limit = null;
    /**
     * matches/searches for objects
     *
     * Generated from protobuf field <code>optional .weaviate.v1.Filters filters = 40;</code>
     */
    protected $filters = null;
    protected $search;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *           required
     *     @type string $tenant
     *           parameters
     *     @type bool $objects_count
     *           what is returned
     *     @type \Weaviate\Client\Proto\V1\AggregateRequest\Aggregation[] $aggregations
     *     @type int $object_limit
     *           affects aggregation results
     *     @type \Weaviate\Client\Proto\V1\AggregateRequest\GroupBy $group_by
     *     @type int $limit
     *     @type \Weaviate\Client\Proto\V1\Filters $filters
     *           matches/searches for objects
     *     @type \Weaviate\Client\Proto\V1\Hybrid $hybrid
     *     @type \Weaviate\Client\Proto\V1\NearVector $near_vector
     *     @type \Weaviate\Client\Proto\V1\NearObject $near_object
     *     @type \Weaviate\Client\Proto\V1\NearTextSearch $near_text
     *     @type \Weaviate\Client\Proto\V1\NearImageSearch $near_image
     *     @type \Weaviate\Client\Proto\V1\NearAudioSearch $near_audio
     *     @type \Weaviate\Client\Proto\V1\NearVideoSearch $near_video
     *     @type \Weaviate\Client\Proto\V1\NearDepthSearch $near_depth
     *     @type \Weaviate\Client\Proto\V1\NearThermalSearch $near_thermal
     *     @type \Weaviate\Client\Proto\V1\NearIMUSearch $near_imu
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Aggregate::initOnce();
        parent::__construct($data);
    }

    /**
     * required
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * required
     *
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection = $var;

        return $this;
    }

    /**
     * parameters
     *
     * Generated from protobuf field <code>string tenant = 10;</code>
     * @return string
     */
    public function getTenant()
    {
        return $this->tenant;
    }

    /**
     * parameters
     *
     * Generated from protobuf field <code>string tenant = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setTenant(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tenant = $var;

        return $this;
    }

    /**
     * what is returned
     *
     * Generated from protobuf field <code>bool objects_count = 20;</code>
     * @return bool
     */
    public function getObjectsCount()
    {
        return $this->objects_count;
    }

    /**
     * what is returned
     *
     * Generated from protobuf field <code>bool objects_count = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setObjectsCount(bool $var)
    {
        $this->objects_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateRequest.Aggregation aggregations = 21;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\AggregateRequest\Aggregation>
     */
    public function getAggregations()
    {
        return $this->aggregations;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.AggregateRequest.Aggregation aggregations = 21;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateRequest\Aggregation[] $var
     * @return $this
     */
    public function setAggregations(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\AggregateRequest\Aggregation::class);
        $this->aggregations = $arr;

        return $this;
    }

    /**
     * affects aggregation results
     *
     * Generated from protobuf field <code>optional uint32 object_limit = 30;</code>
     * @return int
     */
    public function getObjectLimit()
    {
        return isset($this->object_limit) ? $this->object_limit : 0;
    }

    public function hasObjectLimit()
    {
        return isset($this->object_limit);
    }

    public function clearObjectLimit()
    {
        unset($this->object_limit);
    }

    /**
     * affects aggregation results
     *
     * Generated from protobuf field <code>optional uint32 object_limit = 30;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectLimit(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->object_limit = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateRequest.GroupBy group_by = 31;</code>
     * @return \Weaviate\Client\Proto\V1\AggregateRequest\GroupBy|null
     */
    public function getGroupBy()
    {
        return $this->group_by;
    }

    public function hasGroupBy()
    {
        return isset($this->group_by);
    }

    public function clearGroupBy()
    {
        unset($this->group_by);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.AggregateRequest.GroupBy group_by = 31;</code>
     * @param \Weaviate\Client\Proto\V1\AggregateRequest\GroupBy $var
     * @return $this
     */
    public function setGroupBy(\Weaviate\Client\Proto\V1\AggregateRequest\GroupBy|null $var)
    {
        $this->group_by = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 limit = 32;</code>
     * @return int
     */
    public function getLimit()
    {
        return isset($this->limit) ? $this->limit : 0;
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * Generated from protobuf field <code>optional uint32 limit = 32;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->limit = $var;

        return $this;
    }

    /**
     * matches/searches for objects
     *
     * Generated from protobuf field <code>optional .weaviate.v1.Filters filters = 40;</code>
     * @return \Weaviate\Client\Proto\V1\Filters|null
     */
    public function getFilters()
    {
        return $this->filters;
    }

    public function hasFilters()
    {
        return isset($this->filters);
    }

    public function clearFilters()
    {
        unset($this->filters);
    }

    /**
     * matches/searches for objects
     *
     * Generated from protobuf field <code>optional .weaviate.v1.Filters filters = 40;</code>
     * @param \Weaviate\Client\Proto\V1\Filters $var
     * @return $this
     */
    public function setFilters(\Weaviate\Client\Proto\V1\Filters|null $var)
    {
        $this->filters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Hybrid hybrid = 41;</code>
     * @return \Weaviate\Client\Proto\V1\Hybrid|null
     */
    public function getHybrid()
    {
        return $this->readOneof(41);
    }

    public function hasHybrid()
    {
        return $this->hasOneof(41);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Hybrid hybrid = 41;</code>
     * @param \Weaviate\Client\Proto\V1\Hybrid $var
     * @return $this
     */
    public function setHybrid(\Weaviate\Client\Proto\V1\Hybrid|null $var)
    {
        $this->writeOneof(41, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearVector near_vector = 42;</code>
     * @return \Weaviate\Client\Proto\V1\NearVector|null
     */
    public function getNearVector()
    {
        return $this->readOneof(42);
    }

    public function hasNearVector()
    {
        return $this->hasOneof(42);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearVector near_vector = 42;</code>
     * @param \Weaviate\Client\Proto\V1\NearVector $var
     * @return $this
     */
    public function setNearVector(\Weaviate\Client\Proto\V1\NearVector|null $var)
    {
        $this->writeOneof(42, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearObject near_object = 43;</code>
     * @return \Weaviate\Client\Proto\V1\NearObject|null
     */
    public function getNearObject()
    {
        return $this->readOneof(43);
    }

    public function hasNearObject()
    {
        return $this->hasOneof(43);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearObject near_object = 43;</code>
     * @param \Weaviate\Client\Proto\V1\NearObject $var
     * @return $this
     */
    public function setNearObject(\Weaviate\Client\Proto\V1\NearObject|null $var)
    {
        $this->writeOneof(43, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearTextSearch near_text = 44;</code>
     * @return \Weaviate\Client\Proto\V1\NearTextSearch|null
     */
    public function getNearText()
    {
        return $this->readOneof(44);
    }

    public function hasNearText()
    {
        return $this->hasOneof(44);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearTextSearch near_text = 44;</code>
     * @param \Weaviate\Client\Proto\V1\NearTextSearch $var
     * @return $this
     */
    public function setNearText(\Weaviate\Client\Proto\V1\NearTextSearch|null $var)
    {
        $this->writeOneof(44, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearImageSearch near_image = 45;</code>
     * @return \Weaviate\Client\Proto\V1\NearImageSearch|null
     */
    public function getNearImage()
    {
        return $this->readOneof(45);
    }

    public function hasNearImage()
    {
        return $this->hasOneof(45);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearImageSearch near_image = 45;</code>
     * @param \Weaviate\Client\Proto\V1\NearImageSearch $var
     * @return $this
     */
    public function setNearImage(\Weaviate\Client\Proto\V1\NearImageSearch|null $var)
    {
        $this->writeOneof(45, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearAudioSearch near_audio = 46;</code>
     * @return \Weaviate\Client\Proto\V1\NearAudioSearch|null
     */
    public function getNearAudio()
    {
        return $this->readOneof(46);
    }

    public function hasNearAudio()
    {
        return $this->hasOneof(46);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearAudioSearch near_audio = 46;</code>
     * @param \Weaviate\Client\Proto\V1\NearAudioSearch $var
     * @return $this
     */
    public function setNearAudio(\Weaviate\Client\Proto\V1\NearAudioSearch|null $var)
    {
        $this->writeOneof(46, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearVideoSearch near_video = 47;</code>
     * @return \Weaviate\Client\Proto\V1\NearVideoSearch|null
     */
    public function getNearVideo()
    {
        return $this->readOneof(47);
    }

    public function hasNearVideo()
    {
        return $this->hasOneof(47);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearVideoSearch near_video = 47;</code>
     * @param \Weaviate\Client\Proto\V1\NearVideoSearch $var
     * @return $this
     */
    public function setNearVideo(\Weaviate\Client\Proto\V1\NearVideoSearch|null $var)
    {
        $this->writeOneof(47, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearDepthSearch near_depth = 48;</code>
     * @return \Weaviate\Client\Proto\V1\NearDepthSearch|null
     */
    public function getNearDepth()
    {
        return $this->readOneof(48);
    }

    public function hasNearDepth()
    {
        return $this->hasOneof(48);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearDepthSearch near_depth = 48;</code>
     * @param \Weaviate\Client\Proto\V1\NearDepthSearch $var
     * @return $this
     */
    public function setNearDepth(\Weaviate\Client\Proto\V1\NearDepthSearch|null $var)
    {
        $this->writeOneof(48, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearThermalSearch near_thermal = 49;</code>
     * @return \Weaviate\Client\Proto\V1\NearThermalSearch|null
     */
    public function getNearThermal()
    {
        return $this->readOneof(49);
    }

    public function hasNearThermal()
    {
        return $this->hasOneof(49);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearThermalSearch near_thermal = 49;</code>
     * @param \Weaviate\Client\Proto\V1\NearThermalSearch $var
     * @return $this
     */
    public function setNearThermal(\Weaviate\Client\Proto\V1\NearThermalSearch|null $var)
    {
        $this->writeOneof(49, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearIMUSearch near_imu = 50;</code>
     * @return \Weaviate\Client\Proto\V1\NearIMUSearch|null
     */
    public function getNearImu()
    {
        return $this->readOneof(50);
    }

    public function hasNearImu()
    {
        return $this->hasOneof(50);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NearIMUSearch near_imu = 50;</code>
     * @param \Weaviate\Client\Proto\V1\NearIMUSearch $var
     * @return $this
     */
    public function setNearImu(\Weaviate\Client\Proto\V1\NearIMUSearch|null $var)
    {
        $this->writeOneof(50, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getSearch()
    {
        return $this->whichOneof("search");
    }

}

