<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch_delete.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchDeleteRequest</code>
 */
class BatchDeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters filters = 2;</code>
     */
    protected $filters = null;
    /**
     * Generated from protobuf field <code>bool verbose = 3;</code>
     */
    protected $verbose = false;
    /**
     * Generated from protobuf field <code>bool dry_run = 4;</code>
     */
    protected $dry_run = false;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 5;</code>
     */
    protected $consistency_level = null;
    /**
     * Generated from protobuf field <code>optional string tenant = 6;</code>
     */
    protected $tenant = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type \Weaviate\Client\Proto\V1\Filters $filters
     *     @type bool $verbose
     *     @type bool $dry_run
     *     @type int $consistency_level
     *     @type string $tenant
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BatchDelete::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters filters = 2;</code>
     * @return \Weaviate\Client\Proto\V1\Filters|null
     */
    public function getFilters()
    {
        return $this->filters;
    }

    public function hasFilters()
    {
        return isset($this->filters);
    }

    public function clearFilters()
    {
        unset($this->filters);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters filters = 2;</code>
     * @param \Weaviate\Client\Proto\V1\Filters $var
     * @return $this
     */
    public function setFilters(\Weaviate\Client\Proto\V1\Filters|null $var)
    {
        $this->filters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool verbose = 3;</code>
     * @return bool
     */
    public function getVerbose()
    {
        return $this->verbose;
    }

    /**
     * Generated from protobuf field <code>bool verbose = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setVerbose(bool $var)
    {
        $this->verbose = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool dry_run = 4;</code>
     * @return bool
     */
    public function getDryRun()
    {
        return $this->dry_run;
    }

    /**
     * Generated from protobuf field <code>bool dry_run = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDryRun(bool $var)
    {
        $this->dry_run = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 5;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\ConsistencyLevel}
     */
    public function getConsistencyLevel()
    {
        return isset($this->consistency_level) ? $this->consistency_level : 0;
    }

    public function hasConsistencyLevel()
    {
        return isset($this->consistency_level);
    }

    public function clearConsistencyLevel()
    {
        unset($this->consistency_level);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.ConsistencyLevel consistency_level = 5;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\ConsistencyLevel}
     * @return $this
     */
    public function setConsistencyLevel(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\ConsistencyLevel::class);
        $this->consistency_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string tenant = 6;</code>
     * @return string
     */
    public function getTenant()
    {
        return isset($this->tenant) ? $this->tenant : '';
    }

    public function hasTenant()
    {
        return isset($this->tenant);
    }

    public function clearTenant()
    {
        unset($this->tenant);
    }

    /**
     * Generated from protobuf field <code>optional string tenant = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTenant(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tenant = $var;

        return $this;
    }

}

