<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchStreamRequest</code>
 */
class BatchStreamRequest extends \Google\Protobuf\Internal\Message
{
    protected $message;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\BatchStreamRequest\Start $start
     *     @type \Weaviate\Client\Proto\V1\BatchStreamRequest\Data $data
     *     @type \Weaviate\Client\Proto\V1\BatchStreamRequest\Stop $stop
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Start start = 1;</code>
     * @return \Weaviate\Client\Proto\V1\BatchStreamRequest\Start|null
     */
    public function getStart()
    {
        return $this->readOneof(1);
    }

    public function hasStart()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Start start = 1;</code>
     * @param \Weaviate\Client\Proto\V1\BatchStreamRequest\Start $var
     * @return $this
     */
    public function setStart(\Weaviate\Client\Proto\V1\BatchStreamRequest\Start|null $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data data = 2;</code>
     * @return \Weaviate\Client\Proto\V1\BatchStreamRequest\Data|null
     */
    public function getData()
    {
        return $this->readOneof(2);
    }

    public function hasData()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Data data = 2;</code>
     * @param \Weaviate\Client\Proto\V1\BatchStreamRequest\Data $var
     * @return $this
     */
    public function setData(\Weaviate\Client\Proto\V1\BatchStreamRequest\Data|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Stop stop = 3;</code>
     * @return \Weaviate\Client\Proto\V1\BatchStreamRequest\Stop|null
     */
    public function getStop()
    {
        return $this->readOneof(3);
    }

    public function hasStop()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchStreamRequest.Stop stop = 3;</code>
     * @param \Weaviate\Client\Proto\V1\BatchStreamRequest\Stop $var
     * @return $this
     */
    public function setStop(\Weaviate\Client\Proto\V1\BatchStreamRequest\Stop|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMessage()
    {
        return $this->whichOneof("message");
    }

}

