<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchReferencesReply</code>
 */
class BatchReferencesReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float took = 1;</code>
     */
    protected $took = 0.0;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchReferencesReply.BatchError errors = 2;</code>
     */
    private $errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $took
     *     @type \Weaviate\Client\Proto\V1\BatchReferencesReply\BatchError[] $errors
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @return float
     */
    public function getTook()
    {
        return $this->took;
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTook(float $var)
    {
        $this->took = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchReferencesReply.BatchError errors = 2;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\BatchReferencesReply\BatchError>
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchReferencesReply.BatchError errors = 2;</code>
     * @param \Weaviate\Client\Proto\V1\BatchReferencesReply\BatchError[] $var
     * @return $this
     */
    public function setErrors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\BatchReferencesReply\BatchError::class);
        $this->errors = $arr;

        return $this;
    }

}

