<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchReference</code>
 */
class BatchReference extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string from_collection = 2;</code>
     */
    protected $from_collection = '';
    /**
     * Generated from protobuf field <code>string from_uuid = 3;</code>
     */
    protected $from_uuid = '';
    /**
     * Generated from protobuf field <code>optional string to_collection = 4;</code>
     */
    protected $to_collection = null;
    /**
     * Generated from protobuf field <code>string to_uuid = 5;</code>
     */
    protected $to_uuid = '';
    /**
     * Generated from protobuf field <code>string tenant = 6;</code>
     */
    protected $tenant = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $from_collection
     *     @type string $from_uuid
     *     @type string $to_collection
     *     @type string $to_uuid
     *     @type string $tenant
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_collection = 2;</code>
     * @return string
     */
    public function getFromCollection()
    {
        return $this->from_collection;
    }

    /**
     * Generated from protobuf field <code>string from_collection = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFromCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->from_collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_uuid = 3;</code>
     * @return string
     */
    public function getFromUuid()
    {
        return $this->from_uuid;
    }

    /**
     * Generated from protobuf field <code>string from_uuid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFromUuid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->from_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string to_collection = 4;</code>
     * @return string
     */
    public function getToCollection()
    {
        return isset($this->to_collection) ? $this->to_collection : '';
    }

    public function hasToCollection()
    {
        return isset($this->to_collection);
    }

    public function clearToCollection()
    {
        unset($this->to_collection);
    }

    /**
     * Generated from protobuf field <code>optional string to_collection = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->to_collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_uuid = 5;</code>
     * @return string
     */
    public function getToUuid()
    {
        return $this->to_uuid;
    }

    /**
     * Generated from protobuf field <code>string to_uuid = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToUuid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->to_uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tenant = 6;</code>
     * @return string
     */
    public function getTenant()
    {
        return $this->tenant;
    }

    /**
     * Generated from protobuf field <code>string tenant = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTenant(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tenant = $var;

        return $this;
    }

}

