<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchObject</code>
 */
class BatchObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     */
    protected $uuid = '';
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 2 [deprecated = true];</code>
     * @deprecated
     */
    private $vector;
    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchObject.Properties properties = 3;</code>
     */
    protected $properties = null;
    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     */
    protected $collection = '';
    /**
     * Generated from protobuf field <code>string tenant = 5;</code>
     */
    protected $tenant = '';
    /**
     * Generated from protobuf field <code>bytes vector_bytes = 6;</code>
     */
    protected $vector_bytes = '';
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 23;</code>
     */
    private $vectors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type float[] $vector
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type \Weaviate\Client\Proto\V1\BatchObject\Properties $properties
     *     @type string $collection
     *     @type string $tenant
     *     @type string $vector_bytes
     *     @type \Weaviate\Client\Proto\V1\Vectors[] $vectors
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Batch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>string uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->uuid = $var;

        return $this;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 2 [deprecated = true];</code>
     * @return RepeatedField<float>
     * @deprecated
     */
    public function getVector()
    {
        if (count($this->vector) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 2 [deprecated = true];</code>
     * @param float[] $var
     * @return $this
     * @deprecated
     */
    public function setVector(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        if (count($arr) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        $this->vector = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchObject.Properties properties = 3;</code>
     * @return \Weaviate\Client\Proto\V1\BatchObject\Properties|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BatchObject.Properties properties = 3;</code>
     * @param \Weaviate\Client\Proto\V1\BatchObject\Properties $var
     * @return $this
     */
    public function setProperties(\Weaviate\Client\Proto\V1\BatchObject\Properties|null $var)
    {
        $this->properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tenant = 5;</code>
     * @return string
     */
    public function getTenant()
    {
        return $this->tenant;
    }

    /**
     * Generated from protobuf field <code>string tenant = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTenant(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->tenant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes vector_bytes = 6;</code>
     * @return string
     */
    public function getVectorBytes()
    {
        return $this->vector_bytes;
    }

    /**
     * Generated from protobuf field <code>bytes vector_bytes = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setVectorBytes(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->vector_bytes = $var;

        return $this;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 23;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Vectors>
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 23;</code>
     * @param \Weaviate\Client\Proto\V1\Vectors[] $var
     * @return $this
     */
    public function setVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Vectors::class);
        $this->vectors = $arr;

        return $this;
    }

}

