<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch_delete.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchDeleteReply</code>
 */
class BatchDeleteReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float took = 1;</code>
     */
    protected $took = 0.0;
    /**
     * Generated from protobuf field <code>int64 failed = 2;</code>
     */
    protected $failed = 0;
    /**
     * Generated from protobuf field <code>int64 matches = 3;</code>
     */
    protected $matches = 0;
    /**
     * Generated from protobuf field <code>int64 successful = 4;</code>
     */
    protected $successful = 0;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchDeleteObject objects = 5;</code>
     */
    private $objects;
    /**
     * The applied cap, from QUERY_MAXIMUM_RESULTS.
     * matches above limit means the call was capped. matches equal to limit means it was not.
     * An absent field means the server predates this field, not a cap of zero.
     *
     * Generated from protobuf field <code>optional int64 limit = 6;</code>
     */
    protected $limit = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $took
     *     @type int|string $failed
     *     @type int|string $matches
     *     @type int|string $successful
     *     @type \Weaviate\Client\Proto\V1\BatchDeleteObject[] $objects
     *     @type int|string $limit
     *           The applied cap, from QUERY_MAXIMUM_RESULTS.
     *           matches above limit means the call was capped. matches equal to limit means it was not.
     *           An absent field means the server predates this field, not a cap of zero.
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BatchDelete::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @return float
     */
    public function getTook()
    {
        return $this->took;
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTook(float $var)
    {
        $this->took = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 failed = 2;</code>
     * @return int|string
     */
    public function getFailed()
    {
        return $this->failed;
    }

    /**
     * Generated from protobuf field <code>int64 failed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFailed(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->failed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 matches = 3;</code>
     * @return int|string
     */
    public function getMatches()
    {
        return $this->matches;
    }

    /**
     * Generated from protobuf field <code>int64 matches = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMatches(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->matches = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 successful = 4;</code>
     * @return int|string
     */
    public function getSuccessful()
    {
        return $this->successful;
    }

    /**
     * Generated from protobuf field <code>int64 successful = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSuccessful(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->successful = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchDeleteObject objects = 5;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\BatchDeleteObject>
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BatchDeleteObject objects = 5;</code>
     * @param \Weaviate\Client\Proto\V1\BatchDeleteObject[] $var
     * @return $this
     */
    public function setObjects(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\BatchDeleteObject::class);
        $this->objects = $arr;

        return $this;
    }

    /**
     * The applied cap, from QUERY_MAXIMUM_RESULTS.
     * matches above limit means the call was capped. matches equal to limit means it was not.
     * An absent field means the server predates this field, not a cap of zero.
     *
     * Generated from protobuf field <code>optional int64 limit = 6;</code>
     * @return int|string
     */
    public function getLimit()
    {
        return isset($this->limit) ? $this->limit : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasLimit()
    {
        return isset($this->limit);
    }

    public function clearLimit()
    {
        unset($this->limit);
    }

    /**
     * The applied cap, from QUERY_MAXIMUM_RESULTS.
     * matches above limit means the call was capped. matches equal to limit means it was not.
     * An absent field means the server predates this field, not a cap of zero.
     *
     * Generated from protobuf field <code>optional int64 limit = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLimit(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;

        return $this;
    }

}

