<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch_delete.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BatchDeleteObject</code>
 */
class BatchDeleteObject extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes uuid = 1;</code>
     */
    protected $uuid = '';
    /**
     * Generated from protobuf field <code>bool successful = 2;</code>
     */
    protected $successful = false;
    /**
     * empty string means no error
     *
     * Generated from protobuf field <code>optional string error = 3;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uuid
     *     @type bool $successful
     *     @type string $error
     *           empty string means no error
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BatchDelete::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes uuid = 1;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>bytes uuid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool successful = 2;</code>
     * @return bool
     */
    public function getSuccessful()
    {
        return $this->successful;
    }

    /**
     * Generated from protobuf field <code>bool successful = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccessful(bool $var)
    {
        $this->successful = $var;

        return $this;
    }

    /**
     * empty string means no error
     *
     * Generated from protobuf field <code>optional string error = 3;</code>
     * @return string
     */
    public function getError()
    {
        return isset($this->error) ? $this->error : '';
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * empty string means no error
     *
     * Generated from protobuf field <code>optional string error = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setError(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->error = $var;

        return $this;
    }

}

