<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.BM25</code>
 */
class BM25 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string query = 1;</code>
     */
    protected $query = '';
    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     */
    private $properties;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions search_operator = 3;</code>
     */
    protected $search_operator = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $query
     *     @type string[] $properties
     *     @type \Weaviate\Client\Proto\V1\SearchOperatorOptions $search_operator
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     * @return RepeatedField<string>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions search_operator = 3;</code>
     * @return \Weaviate\Client\Proto\V1\SearchOperatorOptions|null
     */
    public function getSearchOperator()
    {
        return $this->search_operator;
    }

    public function hasSearchOperator()
    {
        return isset($this->search_operator);
    }

    public function clearSearchOperator()
    {
        unset($this->search_operator);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions search_operator = 3;</code>
     * @param \Weaviate\Client\Proto\V1\SearchOperatorOptions $var
     * @return $this
     */
    public function setSearchOperator(\Weaviate\Client\Proto\V1\SearchOperatorOptions|null $var)
    {
        $this->search_operator = $var;

        return $this;
    }

}

