<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Boost</code>
 */
class Boost extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Boost.Condition conditions = 1;</code>
     */
    private $conditions;
    /**
     * Generated from protobuf field <code>optional float weight = 2;</code>
     */
    protected $weight = null;
    /**
     * Generated from protobuf field <code>optional uint32 depth = 3;</code>
     */
    protected $depth = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\Boost\Condition[] $conditions
     *     @type float $weight
     *     @type int $depth
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Boost.Condition conditions = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Boost\Condition>
     */
    public function getConditions()
    {
        return $this->conditions;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Boost.Condition conditions = 1;</code>
     * @param \Weaviate\Client\Proto\V1\Boost\Condition[] $var
     * @return $this
     */
    public function setConditions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Boost\Condition::class);
        $this->conditions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float weight = 2;</code>
     * @return float
     */
    public function getWeight()
    {
        return isset($this->weight) ? $this->weight : 0.0;
    }

    public function hasWeight()
    {
        return isset($this->weight);
    }

    public function clearWeight()
    {
        unset($this->weight);
    }

    /**
     * Generated from protobuf field <code>optional float weight = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight(float $var)
    {
        $this->weight = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 depth = 3;</code>
     * @return int
     */
    public function getDepth()
    {
        return isset($this->depth) ? $this->depth : 0;
    }

    public function hasDepth()
    {
        return isset($this->depth);
    }

    public function clearDepth()
    {
        unset($this->depth);
    }

    /**
     * Generated from protobuf field <code>optional uint32 depth = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDepth(int $var)
    {
        GPBUtil::checkUint32($var);
        $this->depth = $var;

        return $this;
    }

}

