<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.CombinationMethod</code>
 */
class CombinationMethod
{
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_UNSPECIFIED = 0;</code>
     */
    const COMBINATION_METHOD_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_TYPE_SUM = 1;</code>
     */
    const COMBINATION_METHOD_TYPE_SUM = 1;
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_TYPE_MIN = 2;</code>
     */
    const COMBINATION_METHOD_TYPE_MIN = 2;
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_TYPE_AVERAGE = 3;</code>
     */
    const COMBINATION_METHOD_TYPE_AVERAGE = 3;
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_TYPE_RELATIVE_SCORE = 4;</code>
     */
    const COMBINATION_METHOD_TYPE_RELATIVE_SCORE = 4;
    /**
     * Generated from protobuf enum <code>COMBINATION_METHOD_TYPE_MANUAL = 5;</code>
     */
    const COMBINATION_METHOD_TYPE_MANUAL = 5;

    private static $valueToName = [
        self::COMBINATION_METHOD_UNSPECIFIED => 'COMBINATION_METHOD_UNSPECIFIED',
        self::COMBINATION_METHOD_TYPE_SUM => 'COMBINATION_METHOD_TYPE_SUM',
        self::COMBINATION_METHOD_TYPE_MIN => 'COMBINATION_METHOD_TYPE_MIN',
        self::COMBINATION_METHOD_TYPE_AVERAGE => 'COMBINATION_METHOD_TYPE_AVERAGE',
        self::COMBINATION_METHOD_TYPE_RELATIVE_SCORE => 'COMBINATION_METHOD_TYPE_RELATIVE_SCORE',
        self::COMBINATION_METHOD_TYPE_MANUAL => 'COMBINATION_METHOD_TYPE_MANUAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

