<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.ConsistencyLevel</code>
 */
class ConsistencyLevel
{
    /**
     * Generated from protobuf enum <code>CONSISTENCY_LEVEL_UNSPECIFIED = 0;</code>
     */
    const CONSISTENCY_LEVEL_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CONSISTENCY_LEVEL_ONE = 1;</code>
     */
    const CONSISTENCY_LEVEL_ONE = 1;
    /**
     * Generated from protobuf enum <code>CONSISTENCY_LEVEL_QUORUM = 2;</code>
     */
    const CONSISTENCY_LEVEL_QUORUM = 2;
    /**
     * Generated from protobuf enum <code>CONSISTENCY_LEVEL_ALL = 3;</code>
     */
    const CONSISTENCY_LEVEL_ALL = 3;

    private static $valueToName = [
        self::CONSISTENCY_LEVEL_UNSPECIFIED => 'CONSISTENCY_LEVEL_UNSPECIFIED',
        self::CONSISTENCY_LEVEL_ONE => 'CONSISTENCY_LEVEL_ONE',
        self::CONSISTENCY_LEVEL_QUORUM => 'CONSISTENCY_LEVEL_QUORUM',
        self::CONSISTENCY_LEVEL_ALL => 'CONSISTENCY_LEVEL_ALL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

