<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Filters</code>
 */
class Filters extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters.Operator operator = 1;</code>
     */
    protected $operator = 0;
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string on = 2 [deprecated = true];</code>
     * @deprecated
     */
    private $on;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Filters filters = 3;</code>
     */
    private $filters;
    /**
     * leave space for more filter values
     *
     * Generated from protobuf field <code>.weaviate.v1.FilterTarget target = 20;</code>
     */
    protected $target = null;
    protected $test_value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $operator
     *     @type string[] $on
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type \Weaviate\Client\Proto\V1\Filters[] $filters
     *     @type string $value_text
     *     @type int|string $value_int
     *     @type bool $value_boolean
     *     @type float $value_number
     *     @type \Weaviate\Client\Proto\V1\TextArray $value_text_array
     *     @type \Weaviate\Client\Proto\V1\IntArray $value_int_array
     *     @type \Weaviate\Client\Proto\V1\BooleanArray $value_boolean_array
     *     @type \Weaviate\Client\Proto\V1\NumberArray $value_number_array
     *     @type \Weaviate\Client\Proto\V1\GeoCoordinatesFilter $value_geo
     *     @type \Weaviate\Client\Proto\V1\FilterTarget $target
     *           leave space for more filter values
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters.Operator operator = 1;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\Filters\Operator}
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Filters.Operator operator = 1;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\Filters\Operator}
     * @return $this
     */
    public function setOperator(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\Filters\Operator::class);
        $this->operator = $var;

        return $this;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string on = 2 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getOn()
    {
        if (count($this->on) !== 0) {
            @trigger_error('on is deprecated.', E_USER_DEPRECATED);
        }
        return $this->on;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string on = 2 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setOn(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('on is deprecated.', E_USER_DEPRECATED);
        }
        $this->on = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Filters filters = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Filters>
     */
    public function getFilters()
    {
        return $this->filters;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Filters filters = 3;</code>
     * @param \Weaviate\Client\Proto\V1\Filters[] $var
     * @return $this
     */
    public function setFilters(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Filters::class);
        $this->filters = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value_text = 4;</code>
     * @return string
     */
    public function getValueText()
    {
        return $this->readOneof(4);
    }

    public function hasValueText()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>string value_text = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setValueText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 value_int = 5;</code>
     * @return int|string
     */
    public function getValueInt()
    {
        return $this->readOneof(5);
    }

    public function hasValueInt()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>int64 value_int = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValueInt(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool value_boolean = 6;</code>
     * @return bool
     */
    public function getValueBoolean()
    {
        return $this->readOneof(6);
    }

    public function hasValueBoolean()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>bool value_boolean = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setValueBoolean(bool $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double value_number = 7;</code>
     * @return float
     */
    public function getValueNumber()
    {
        return $this->readOneof(7);
    }

    public function hasValueNumber()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>double value_number = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setValueNumber(float $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextArray value_text_array = 9;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getValueTextArray()
    {
        return $this->readOneof(9);
    }

    public function hasValueTextArray()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextArray value_text_array = 9;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setValueTextArray(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntArray value_int_array = 10;</code>
     * @return \Weaviate\Client\Proto\V1\IntArray|null
     */
    public function getValueIntArray()
    {
        return $this->readOneof(10);
    }

    public function hasValueIntArray()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntArray value_int_array = 10;</code>
     * @param \Weaviate\Client\Proto\V1\IntArray $var
     * @return $this
     */
    public function setValueIntArray(\Weaviate\Client\Proto\V1\IntArray|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BooleanArray value_boolean_array = 11;</code>
     * @return \Weaviate\Client\Proto\V1\BooleanArray|null
     */
    public function getValueBooleanArray()
    {
        return $this->readOneof(11);
    }

    public function hasValueBooleanArray()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BooleanArray value_boolean_array = 11;</code>
     * @param \Weaviate\Client\Proto\V1\BooleanArray $var
     * @return $this
     */
    public function setValueBooleanArray(\Weaviate\Client\Proto\V1\BooleanArray|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberArray value_number_array = 12;</code>
     * @return \Weaviate\Client\Proto\V1\NumberArray|null
     */
    public function getValueNumberArray()
    {
        return $this->readOneof(12);
    }

    public function hasValueNumberArray()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberArray value_number_array = 12;</code>
     * @param \Weaviate\Client\Proto\V1\NumberArray $var
     * @return $this
     */
    public function setValueNumberArray(\Weaviate\Client\Proto\V1\NumberArray|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinatesFilter value_geo = 13;</code>
     * @return \Weaviate\Client\Proto\V1\GeoCoordinatesFilter|null
     */
    public function getValueGeo()
    {
        return $this->readOneof(13);
    }

    public function hasValueGeo()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinatesFilter value_geo = 13;</code>
     * @param \Weaviate\Client\Proto\V1\GeoCoordinatesFilter $var
     * @return $this
     */
    public function setValueGeo(\Weaviate\Client\Proto\V1\GeoCoordinatesFilter|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * leave space for more filter values
     *
     * Generated from protobuf field <code>.weaviate.v1.FilterTarget target = 20;</code>
     * @return \Weaviate\Client\Proto\V1\FilterTarget|null
     */
    public function getTarget()
    {
        return $this->target;
    }

    public function hasTarget()
    {
        return isset($this->target);
    }

    public function clearTarget()
    {
        unset($this->target);
    }

    /**
     * leave space for more filter values
     *
     * Generated from protobuf field <code>.weaviate.v1.FilterTarget target = 20;</code>
     * @param \Weaviate\Client\Proto\V1\FilterTarget $var
     * @return $this
     */
    public function setTarget(\Weaviate\Client\Proto\V1\FilterTarget|null $var)
    {
        $this->target = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getTestValue()
    {
        return $this->whichOneof("test_value");
    }

}

