<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.FilterReferenceCount</code>
 */
class FilterReferenceCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string on = 1;</code>
     */
    protected $on = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $on
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string on = 1;</code>
     * @return string
     */
    public function getOn()
    {
        return $this->on;
    }

    /**
     * Generated from protobuf field <code>string on = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOn(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->on = $var;

        return $this;
    }

}

