<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeProvider</code>
 */
class GenerativeProvider extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool return_metadata = 1;</code>
     */
    protected $return_metadata = false;
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $return_metadata
     *     @type \Weaviate\Client\Proto\V1\GenerativeAnthropic $anthropic
     *     @type \Weaviate\Client\Proto\V1\GenerativeAnyscale $anyscale
     *     @type \Weaviate\Client\Proto\V1\GenerativeAWS $aws
     *     @type \Weaviate\Client\Proto\V1\GenerativeCohere $cohere
     *     @type \Weaviate\Client\Proto\V1\GenerativeDummy $dummy
     *     @type \Weaviate\Client\Proto\V1\GenerativeMistral $mistral
     *     @type \Weaviate\Client\Proto\V1\GenerativeOllama $ollama
     *     @type \Weaviate\Client\Proto\V1\GenerativeOpenAI $openai
     *     @type \Weaviate\Client\Proto\V1\GenerativeGoogle $google
     *     @type \Weaviate\Client\Proto\V1\GenerativeDatabricks $databricks
     *     @type \Weaviate\Client\Proto\V1\GenerativeFriendliAI $friendliai
     *     @type \Weaviate\Client\Proto\V1\GenerativeNvidia $nvidia
     *     @type \Weaviate\Client\Proto\V1\GenerativeXAI $xai
     *     @type \Weaviate\Client\Proto\V1\GenerativeContextualAI $contextualai
     *     @type \Weaviate\Client\Proto\V1\GenerativeDeepseek $deepseek
     *     @type \Weaviate\Client\Proto\V1\GenerativeDigitalOcean $digitalocean
     *     @type \Weaviate\Client\Proto\V1\GenerativeMeta $meta
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool return_metadata = 1;</code>
     * @return bool
     */
    public function getReturnMetadata()
    {
        return $this->return_metadata;
    }

    /**
     * Generated from protobuf field <code>bool return_metadata = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnMetadata(bool $var)
    {
        $this->return_metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAnthropic anthropic = 2;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeAnthropic|null
     */
    public function getAnthropic()
    {
        return $this->readOneof(2);
    }

    public function hasAnthropic()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAnthropic anthropic = 2;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeAnthropic $var
     * @return $this
     */
    public function setAnthropic(\Weaviate\Client\Proto\V1\GenerativeAnthropic|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAnyscale anyscale = 3;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeAnyscale|null
     */
    public function getAnyscale()
    {
        return $this->readOneof(3);
    }

    public function hasAnyscale()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAnyscale anyscale = 3;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeAnyscale $var
     * @return $this
     */
    public function setAnyscale(\Weaviate\Client\Proto\V1\GenerativeAnyscale|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAWS aws = 4;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeAWS|null
     */
    public function getAws()
    {
        return $this->readOneof(4);
    }

    public function hasAws()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeAWS aws = 4;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeAWS $var
     * @return $this
     */
    public function setAws(\Weaviate\Client\Proto\V1\GenerativeAWS|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeCohere cohere = 5;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeCohere|null
     */
    public function getCohere()
    {
        return $this->readOneof(5);
    }

    public function hasCohere()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeCohere cohere = 5;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeCohere $var
     * @return $this
     */
    public function setCohere(\Weaviate\Client\Proto\V1\GenerativeCohere|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDummy dummy = 6;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeDummy|null
     */
    public function getDummy()
    {
        return $this->readOneof(6);
    }

    public function hasDummy()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDummy dummy = 6;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeDummy $var
     * @return $this
     */
    public function setDummy(\Weaviate\Client\Proto\V1\GenerativeDummy|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeMistral mistral = 7;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeMistral|null
     */
    public function getMistral()
    {
        return $this->readOneof(7);
    }

    public function hasMistral()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeMistral mistral = 7;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeMistral $var
     * @return $this
     */
    public function setMistral(\Weaviate\Client\Proto\V1\GenerativeMistral|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeOllama ollama = 8;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeOllama|null
     */
    public function getOllama()
    {
        return $this->readOneof(8);
    }

    public function hasOllama()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeOllama ollama = 8;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeOllama $var
     * @return $this
     */
    public function setOllama(\Weaviate\Client\Proto\V1\GenerativeOllama|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeOpenAI openai = 9;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeOpenAI|null
     */
    public function getOpenai()
    {
        return $this->readOneof(9);
    }

    public function hasOpenai()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeOpenAI openai = 9;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeOpenAI $var
     * @return $this
     */
    public function setOpenai(\Weaviate\Client\Proto\V1\GenerativeOpenAI|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeGoogle google = 10;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeGoogle|null
     */
    public function getGoogle()
    {
        return $this->readOneof(10);
    }

    public function hasGoogle()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeGoogle google = 10;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeGoogle $var
     * @return $this
     */
    public function setGoogle(\Weaviate\Client\Proto\V1\GenerativeGoogle|null $var)
    {
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDatabricks databricks = 11;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeDatabricks|null
     */
    public function getDatabricks()
    {
        return $this->readOneof(11);
    }

    public function hasDatabricks()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDatabricks databricks = 11;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeDatabricks $var
     * @return $this
     */
    public function setDatabricks(\Weaviate\Client\Proto\V1\GenerativeDatabricks|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeFriendliAI friendliai = 12;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeFriendliAI|null
     */
    public function getFriendliai()
    {
        return $this->readOneof(12);
    }

    public function hasFriendliai()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeFriendliAI friendliai = 12;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeFriendliAI $var
     * @return $this
     */
    public function setFriendliai(\Weaviate\Client\Proto\V1\GenerativeFriendliAI|null $var)
    {
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeNvidia nvidia = 13;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeNvidia|null
     */
    public function getNvidia()
    {
        return $this->readOneof(13);
    }

    public function hasNvidia()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeNvidia nvidia = 13;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeNvidia $var
     * @return $this
     */
    public function setNvidia(\Weaviate\Client\Proto\V1\GenerativeNvidia|null $var)
    {
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeXAI xai = 14;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeXAI|null
     */
    public function getXai()
    {
        return $this->readOneof(14);
    }

    public function hasXai()
    {
        return $this->hasOneof(14);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeXAI xai = 14;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeXAI $var
     * @return $this
     */
    public function setXai(\Weaviate\Client\Proto\V1\GenerativeXAI|null $var)
    {
        $this->writeOneof(14, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeContextualAI contextualai = 15;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeContextualAI|null
     */
    public function getContextualai()
    {
        return $this->readOneof(15);
    }

    public function hasContextualai()
    {
        return $this->hasOneof(15);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeContextualAI contextualai = 15;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeContextualAI $var
     * @return $this
     */
    public function setContextualai(\Weaviate\Client\Proto\V1\GenerativeContextualAI|null $var)
    {
        $this->writeOneof(15, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDeepseek deepseek = 16;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeDeepseek|null
     */
    public function getDeepseek()
    {
        return $this->readOneof(16);
    }

    public function hasDeepseek()
    {
        return $this->hasOneof(16);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDeepseek deepseek = 16;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeDeepseek $var
     * @return $this
     */
    public function setDeepseek(\Weaviate\Client\Proto\V1\GenerativeDeepseek|null $var)
    {
        $this->writeOneof(16, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDigitalOcean digitalocean = 17;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeDigitalOcean|null
     */
    public function getDigitalocean()
    {
        return $this->readOneof(17);
    }

    public function hasDigitalocean()
    {
        return $this->hasOneof(17);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeDigitalOcean digitalocean = 17;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeDigitalOcean $var
     * @return $this
     */
    public function setDigitalocean(\Weaviate\Client\Proto\V1\GenerativeDigitalOcean|null $var)
    {
        $this->writeOneof(17, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeMeta meta = 18;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeMeta|null
     */
    public function getMeta()
    {
        return $this->readOneof(18);
    }

    public function hasMeta()
    {
        return $this->hasOneof(18);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeMeta meta = 18;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeMeta $var
     * @return $this
     */
    public function setMeta(\Weaviate\Client\Proto\V1\GenerativeMeta|null $var)
    {
        $this->writeOneof(18, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

