<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeSearch</code>
 */
class GenerativeSearch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string single_response_prompt = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $single_response_prompt = '';
    /**
     * Generated from protobuf field <code>string grouped_response_task = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $grouped_response_task = '';
    /**
     * Generated from protobuf field <code>repeated string grouped_properties = 3 [deprecated = true];</code>
     * @deprecated
     */
    private $grouped_properties;
    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Single single = 4;</code>
     */
    protected $single = null;
    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Grouped grouped = 5;</code>
     */
    protected $grouped = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $single_response_prompt
     *     @type string $grouped_response_task
     *     @type string[] $grouped_properties
     *     @type \Weaviate\Client\Proto\V1\GenerativeSearch\Single $single
     *     @type \Weaviate\Client\Proto\V1\GenerativeSearch\Grouped $grouped
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string single_response_prompt = 1 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getSingleResponsePrompt()
    {
        if ($this->single_response_prompt !== '') {
            @trigger_error('single_response_prompt is deprecated.', E_USER_DEPRECATED);
        }
        return $this->single_response_prompt;
    }

    /**
     * Generated from protobuf field <code>string single_response_prompt = 1 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setSingleResponsePrompt(string $var)
    {
        @trigger_error('single_response_prompt is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->single_response_prompt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string grouped_response_task = 2 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getGroupedResponseTask()
    {
        if ($this->grouped_response_task !== '') {
            @trigger_error('grouped_response_task is deprecated.', E_USER_DEPRECATED);
        }
        return $this->grouped_response_task;
    }

    /**
     * Generated from protobuf field <code>string grouped_response_task = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setGroupedResponseTask(string $var)
    {
        @trigger_error('grouped_response_task is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->grouped_response_task = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string grouped_properties = 3 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getGroupedProperties()
    {
        if (count($this->grouped_properties) !== 0) {
            @trigger_error('grouped_properties is deprecated.', E_USER_DEPRECATED);
        }
        return $this->grouped_properties;
    }

    /**
     * Generated from protobuf field <code>repeated string grouped_properties = 3 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setGroupedProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('grouped_properties is deprecated.', E_USER_DEPRECATED);
        }
        $this->grouped_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Single single = 4;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeSearch\Single|null
     */
    public function getSingle()
    {
        return $this->single;
    }

    public function hasSingle()
    {
        return isset($this->single);
    }

    public function clearSingle()
    {
        unset($this->single);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Single single = 4;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeSearch\Single $var
     * @return $this
     */
    public function setSingle(\Weaviate\Client\Proto\V1\GenerativeSearch\Single|null $var)
    {
        $this->single = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Grouped grouped = 5;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeSearch\Grouped|null
     */
    public function getGrouped()
    {
        return $this->grouped;
    }

    public function hasGrouped()
    {
        return isset($this->grouped);
    }

    public function clearGrouped()
    {
        unset($this->grouped);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GenerativeSearch.Grouped grouped = 5;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeSearch\Grouped $var
     * @return $this
     */
    public function setGrouped(\Weaviate\Client\Proto\V1\GenerativeSearch\Grouped|null $var)
    {
        $this->grouped = $var;

        return $this;
    }

}

