<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeContextualAI</code>
 */
class GenerativeContextualAI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string model = 1;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>optional double temperature = 2;</code>
     */
    protected $temperature = null;
    /**
     * Generated from protobuf field <code>optional double top_p = 3;</code>
     */
    protected $top_p = null;
    /**
     * Generated from protobuf field <code>optional int64 max_new_tokens = 4;</code>
     */
    protected $max_new_tokens = null;
    /**
     * Generated from protobuf field <code>optional string system_prompt = 5;</code>
     */
    protected $system_prompt = null;
    /**
     * Generated from protobuf field <code>optional bool avoid_commentary = 6;</code>
     */
    protected $avoid_commentary = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray knowledge = 7;</code>
     */
    protected $knowledge = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model
     *     @type float $temperature
     *     @type float $top_p
     *     @type int|string $max_new_tokens
     *     @type string $system_prompt
     *     @type bool $avoid_commentary
     *     @type \Weaviate\Client\Proto\V1\TextArray $knowledge
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string model = 1;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 2;</code>
     * @return float
     */
    public function getTemperature()
    {
        return isset($this->temperature) ? $this->temperature : 0.0;
    }

    public function hasTemperature()
    {
        return isset($this->temperature);
    }

    public function clearTemperature()
    {
        unset($this->temperature);
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setTemperature(float $var)
    {
        $this->temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double top_p = 3;</code>
     * @return float
     */
    public function getTopP()
    {
        return isset($this->top_p) ? $this->top_p : 0.0;
    }

    public function hasTopP()
    {
        return isset($this->top_p);
    }

    public function clearTopP()
    {
        unset($this->top_p);
    }

    /**
     * Generated from protobuf field <code>optional double top_p = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTopP(float $var)
    {
        $this->top_p = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 max_new_tokens = 4;</code>
     * @return int|string
     */
    public function getMaxNewTokens()
    {
        return isset($this->max_new_tokens) ? $this->max_new_tokens : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasMaxNewTokens()
    {
        return isset($this->max_new_tokens);
    }

    public function clearMaxNewTokens()
    {
        unset($this->max_new_tokens);
    }

    /**
     * Generated from protobuf field <code>optional int64 max_new_tokens = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxNewTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->max_new_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string system_prompt = 5;</code>
     * @return string
     */
    public function getSystemPrompt()
    {
        return isset($this->system_prompt) ? $this->system_prompt : '';
    }

    public function hasSystemPrompt()
    {
        return isset($this->system_prompt);
    }

    public function clearSystemPrompt()
    {
        unset($this->system_prompt);
    }

    /**
     * Generated from protobuf field <code>optional string system_prompt = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSystemPrompt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->system_prompt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool avoid_commentary = 6;</code>
     * @return bool
     */
    public function getAvoidCommentary()
    {
        return isset($this->avoid_commentary) ? $this->avoid_commentary : false;
    }

    public function hasAvoidCommentary()
    {
        return isset($this->avoid_commentary);
    }

    public function clearAvoidCommentary()
    {
        unset($this->avoid_commentary);
    }

    /**
     * Generated from protobuf field <code>optional bool avoid_commentary = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAvoidCommentary(bool $var)
    {
        $this->avoid_commentary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray knowledge = 7;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getKnowledge()
    {
        return $this->knowledge;
    }

    public function hasKnowledge()
    {
        return isset($this->knowledge);
    }

    public function clearKnowledge()
    {
        unset($this->knowledge);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray knowledge = 7;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setKnowledge(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->knowledge = $var;

        return $this;
    }

}

