<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeDebug</code>
 */
class GenerativeDebug extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string full_prompt = 1;</code>
     */
    protected $full_prompt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $full_prompt
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string full_prompt = 1;</code>
     * @return string
     */
    public function getFullPrompt()
    {
        return isset($this->full_prompt) ? $this->full_prompt : '';
    }

    public function hasFullPrompt()
    {
        return isset($this->full_prompt);
    }

    public function clearFullPrompt()
    {
        unset($this->full_prompt);
    }

    /**
     * Generated from protobuf field <code>optional string full_prompt = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFullPrompt(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->full_prompt = $var;

        return $this;
    }

}

