<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeAnyscale</code>
 */
class GenerativeAnyscale extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string base_url = 1;</code>
     */
    protected $base_url = null;
    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     */
    protected $temperature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base_url
     *     @type string $model
     *     @type float $temperature
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string base_url = 1;</code>
     * @return string
     */
    public function getBaseUrl()
    {
        return isset($this->base_url) ? $this->base_url : '';
    }

    public function hasBaseUrl()
    {
        return isset($this->base_url);
    }

    public function clearBaseUrl()
    {
        unset($this->base_url);
    }

    /**
     * Generated from protobuf field <code>optional string base_url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->base_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     * @return float
     */
    public function getTemperature()
    {
        return isset($this->temperature) ? $this->temperature : 0.0;
    }

    public function hasTemperature()
    {
        return isset($this->temperature);
    }

    public function clearTemperature()
    {
        unset($this->temperature);
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTemperature(float $var)
    {
        $this->temperature = $var;

        return $this;
    }

}

