<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeAWS</code>
 */
class GenerativeAWS extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>optional double temperature = 8;</code>
     */
    protected $temperature = null;
    /**
     * Generated from protobuf field <code>optional string service = 9;</code>
     */
    protected $service = null;
    /**
     * Generated from protobuf field <code>optional string region = 10;</code>
     */
    protected $region = null;
    /**
     * Generated from protobuf field <code>optional string endpoint = 11;</code>
     */
    protected $endpoint = null;
    /**
     * Generated from protobuf field <code>optional string target_model = 12;</code>
     */
    protected $target_model = null;
    /**
     * Generated from protobuf field <code>optional string target_variant = 13;</code>
     */
    protected $target_variant = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     */
    protected $images = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     */
    protected $image_properties = null;
    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 16;</code>
     */
    protected $max_tokens = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop_sequences = 17;</code>
     */
    protected $stop_sequences = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $model
     *     @type float $temperature
     *     @type string $service
     *     @type string $region
     *     @type string $endpoint
     *     @type string $target_model
     *     @type string $target_variant
     *     @type \Weaviate\Client\Proto\V1\TextArray $images
     *     @type \Weaviate\Client\Proto\V1\TextArray $image_properties
     *     @type int|string $max_tokens
     *     @type \Weaviate\Client\Proto\V1\TextArray $stop_sequences
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 8;</code>
     * @return float
     */
    public function getTemperature()
    {
        return isset($this->temperature) ? $this->temperature : 0.0;
    }

    public function hasTemperature()
    {
        return isset($this->temperature);
    }

    public function clearTemperature()
    {
        unset($this->temperature);
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setTemperature(float $var)
    {
        $this->temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string service = 9;</code>
     * @return string
     */
    public function getService()
    {
        return isset($this->service) ? $this->service : '';
    }

    public function hasService()
    {
        return isset($this->service);
    }

    public function clearService()
    {
        unset($this->service);
    }

    /**
     * Generated from protobuf field <code>optional string service = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setService(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->service = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string region = 10;</code>
     * @return string
     */
    public function getRegion()
    {
        return isset($this->region) ? $this->region : '';
    }

    public function hasRegion()
    {
        return isset($this->region);
    }

    public function clearRegion()
    {
        unset($this->region);
    }

    /**
     * Generated from protobuf field <code>optional string region = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRegion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->region = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string endpoint = 11;</code>
     * @return string
     */
    public function getEndpoint()
    {
        return isset($this->endpoint) ? $this->endpoint : '';
    }

    public function hasEndpoint()
    {
        return isset($this->endpoint);
    }

    public function clearEndpoint()
    {
        unset($this->endpoint);
    }

    /**
     * Generated from protobuf field <code>optional string endpoint = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string target_model = 12;</code>
     * @return string
     */
    public function getTargetModel()
    {
        return isset($this->target_model) ? $this->target_model : '';
    }

    public function hasTargetModel()
    {
        return isset($this->target_model);
    }

    public function clearTargetModel()
    {
        unset($this->target_model);
    }

    /**
     * Generated from protobuf field <code>optional string target_model = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target_model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string target_variant = 13;</code>
     * @return string
     */
    public function getTargetVariant()
    {
        return isset($this->target_variant) ? $this->target_variant : '';
    }

    public function hasTargetVariant()
    {
        return isset($this->target_variant);
    }

    public function clearTargetVariant()
    {
        unset($this->target_variant);
    }

    /**
     * Generated from protobuf field <code>optional string target_variant = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetVariant(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target_variant = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImages()
    {
        return $this->images;
    }

    public function hasImages()
    {
        return isset($this->images);
    }

    public function clearImages()
    {
        unset($this->images);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImages(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->images = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImageProperties()
    {
        return $this->image_properties;
    }

    public function hasImageProperties()
    {
        return isset($this->image_properties);
    }

    public function clearImageProperties()
    {
        unset($this->image_properties);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImageProperties(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->image_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 16;</code>
     * @return int|string
     */
    public function getMaxTokens()
    {
        return isset($this->max_tokens) ? $this->max_tokens : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasMaxTokens()
    {
        return isset($this->max_tokens);
    }

    public function clearMaxTokens()
    {
        unset($this->max_tokens);
    }

    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 16;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->max_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop_sequences = 17;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getStopSequences()
    {
        return $this->stop_sequences;
    }

    public function hasStopSequences()
    {
        return isset($this->stop_sequences);
    }

    public function clearStopSequences()
    {
        unset($this->stop_sequences);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop_sequences = 17;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setStopSequences(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->stop_sequences = $var;

        return $this;
    }

}

