<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeOpenAI</code>
 */
class GenerativeOpenAI extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional double frequency_penalty = 1;</code>
     */
    protected $frequency_penalty = null;
    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 2;</code>
     */
    protected $max_tokens = null;
    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>optional int64 n = 4;</code>
     */
    protected $n = null;
    /**
     * Generated from protobuf field <code>optional double presence_penalty = 5;</code>
     */
    protected $presence_penalty = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop = 6;</code>
     */
    protected $stop = null;
    /**
     * Generated from protobuf field <code>optional double temperature = 7;</code>
     */
    protected $temperature = null;
    /**
     * Generated from protobuf field <code>optional double top_p = 8;</code>
     */
    protected $top_p = null;
    /**
     * Generated from protobuf field <code>optional string base_url = 9;</code>
     */
    protected $base_url = null;
    /**
     * Generated from protobuf field <code>optional string api_version = 10;</code>
     */
    protected $api_version = null;
    /**
     * Generated from protobuf field <code>optional string resource_name = 11;</code>
     */
    protected $resource_name = null;
    /**
     * Generated from protobuf field <code>optional string deployment_id = 12;</code>
     */
    protected $deployment_id = null;
    /**
     * Generated from protobuf field <code>optional bool is_azure = 13;</code>
     */
    protected $is_azure = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     */
    protected $images = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     */
    protected $image_properties = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.ReasoningEffort reasoning_effort = 16;</code>
     */
    protected $reasoning_effort = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.Verbosity verbosity = 17;</code>
     */
    protected $verbosity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $frequency_penalty
     *     @type int|string $max_tokens
     *     @type string $model
     *     @type int|string $n
     *     @type float $presence_penalty
     *     @type \Weaviate\Client\Proto\V1\TextArray $stop
     *     @type float $temperature
     *     @type float $top_p
     *     @type string $base_url
     *     @type string $api_version
     *     @type string $resource_name
     *     @type string $deployment_id
     *     @type bool $is_azure
     *     @type \Weaviate\Client\Proto\V1\TextArray $images
     *     @type \Weaviate\Client\Proto\V1\TextArray $image_properties
     *     @type int $reasoning_effort
     *     @type int $verbosity
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional double frequency_penalty = 1;</code>
     * @return float
     */
    public function getFrequencyPenalty()
    {
        return isset($this->frequency_penalty) ? $this->frequency_penalty : 0.0;
    }

    public function hasFrequencyPenalty()
    {
        return isset($this->frequency_penalty);
    }

    public function clearFrequencyPenalty()
    {
        unset($this->frequency_penalty);
    }

    /**
     * Generated from protobuf field <code>optional double frequency_penalty = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setFrequencyPenalty(float $var)
    {
        $this->frequency_penalty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 2;</code>
     * @return int|string
     */
    public function getMaxTokens()
    {
        return isset($this->max_tokens) ? $this->max_tokens : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasMaxTokens()
    {
        return isset($this->max_tokens);
    }

    public function clearMaxTokens()
    {
        unset($this->max_tokens);
    }

    /**
     * Generated from protobuf field <code>optional int64 max_tokens = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMaxTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->max_tokens = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 n = 4;</code>
     * @return int|string
     */
    public function getN()
    {
        return isset($this->n) ? $this->n : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasN()
    {
        return isset($this->n);
    }

    public function clearN()
    {
        unset($this->n);
    }

    /**
     * Generated from protobuf field <code>optional int64 n = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setN(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->n = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double presence_penalty = 5;</code>
     * @return float
     */
    public function getPresencePenalty()
    {
        return isset($this->presence_penalty) ? $this->presence_penalty : 0.0;
    }

    public function hasPresencePenalty()
    {
        return isset($this->presence_penalty);
    }

    public function clearPresencePenalty()
    {
        unset($this->presence_penalty);
    }

    /**
     * Generated from protobuf field <code>optional double presence_penalty = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPresencePenalty(float $var)
    {
        $this->presence_penalty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop = 6;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getStop()
    {
        return $this->stop;
    }

    public function hasStop()
    {
        return isset($this->stop);
    }

    public function clearStop()
    {
        unset($this->stop);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray stop = 6;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setStop(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->stop = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 7;</code>
     * @return float
     */
    public function getTemperature()
    {
        return isset($this->temperature) ? $this->temperature : 0.0;
    }

    public function hasTemperature()
    {
        return isset($this->temperature);
    }

    public function clearTemperature()
    {
        unset($this->temperature);
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setTemperature(float $var)
    {
        $this->temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double top_p = 8;</code>
     * @return float
     */
    public function getTopP()
    {
        return isset($this->top_p) ? $this->top_p : 0.0;
    }

    public function hasTopP()
    {
        return isset($this->top_p);
    }

    public function clearTopP()
    {
        unset($this->top_p);
    }

    /**
     * Generated from protobuf field <code>optional double top_p = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setTopP(float $var)
    {
        $this->top_p = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string base_url = 9;</code>
     * @return string
     */
    public function getBaseUrl()
    {
        return isset($this->base_url) ? $this->base_url : '';
    }

    public function hasBaseUrl()
    {
        return isset($this->base_url);
    }

    public function clearBaseUrl()
    {
        unset($this->base_url);
    }

    /**
     * Generated from protobuf field <code>optional string base_url = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setBaseUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->base_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string api_version = 10;</code>
     * @return string
     */
    public function getApiVersion()
    {
        return isset($this->api_version) ? $this->api_version : '';
    }

    public function hasApiVersion()
    {
        return isset($this->api_version);
    }

    public function clearApiVersion()
    {
        unset($this->api_version);
    }

    /**
     * Generated from protobuf field <code>optional string api_version = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setApiVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->api_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string resource_name = 11;</code>
     * @return string
     */
    public function getResourceName()
    {
        return isset($this->resource_name) ? $this->resource_name : '';
    }

    public function hasResourceName()
    {
        return isset($this->resource_name);
    }

    public function clearResourceName()
    {
        unset($this->resource_name);
    }

    /**
     * Generated from protobuf field <code>optional string resource_name = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setResourceName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->resource_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string deployment_id = 12;</code>
     * @return string
     */
    public function getDeploymentId()
    {
        return isset($this->deployment_id) ? $this->deployment_id : '';
    }

    public function hasDeploymentId()
    {
        return isset($this->deployment_id);
    }

    public function clearDeploymentId()
    {
        unset($this->deployment_id);
    }

    /**
     * Generated from protobuf field <code>optional string deployment_id = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDeploymentId(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->deployment_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool is_azure = 13;</code>
     * @return bool
     */
    public function getIsAzure()
    {
        return isset($this->is_azure) ? $this->is_azure : false;
    }

    public function hasIsAzure()
    {
        return isset($this->is_azure);
    }

    public function clearIsAzure()
    {
        unset($this->is_azure);
    }

    /**
     * Generated from protobuf field <code>optional bool is_azure = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAzure(bool $var)
    {
        $this->is_azure = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImages()
    {
        return $this->images;
    }

    public function hasImages()
    {
        return isset($this->images);
    }

    public function clearImages()
    {
        unset($this->images);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 14;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImages(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->images = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImageProperties()
    {
        return $this->image_properties;
    }

    public function hasImageProperties()
    {
        return isset($this->image_properties);
    }

    public function clearImageProperties()
    {
        unset($this->image_properties);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 15;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImageProperties(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->image_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.ReasoningEffort reasoning_effort = 16;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\GenerativeOpenAI\ReasoningEffort}
     */
    public function getReasoningEffort()
    {
        return isset($this->reasoning_effort) ? $this->reasoning_effort : 0;
    }

    public function hasReasoningEffort()
    {
        return isset($this->reasoning_effort);
    }

    public function clearReasoningEffort()
    {
        unset($this->reasoning_effort);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.ReasoningEffort reasoning_effort = 16;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\GenerativeOpenAI\ReasoningEffort}
     * @return $this
     */
    public function setReasoningEffort(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\GenerativeOpenAI\ReasoningEffort::class);
        $this->reasoning_effort = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.Verbosity verbosity = 17;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\GenerativeOpenAI\Verbosity}
     */
    public function getVerbosity()
    {
        return isset($this->verbosity) ? $this->verbosity : 0;
    }

    public function hasVerbosity()
    {
        return isset($this->verbosity);
    }

    public function clearVerbosity()
    {
        unset($this->verbosity);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeOpenAI.Verbosity verbosity = 17;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\GenerativeOpenAI\Verbosity}
     * @return $this
     */
    public function setVerbosity(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\GenerativeOpenAI\Verbosity::class);
        $this->verbosity = $var;

        return $this;
    }

}

