<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeMetaMetadata</code>
 */
class GenerativeMetaMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetaMetadata.Usage usage = 1;</code>
     */
    protected $usage = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\GenerativeMetaMetadata\Usage $usage
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetaMetadata.Usage usage = 1;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeMetaMetadata\Usage|null
     */
    public function getUsage()
    {
        return $this->usage;
    }

    public function hasUsage()
    {
        return isset($this->usage);
    }

    public function clearUsage()
    {
        unset($this->usage);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetaMetadata.Usage usage = 1;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeMetaMetadata\Usage $var
     * @return $this
     */
    public function setUsage(\Weaviate\Client\Proto\V1\GenerativeMetaMetadata\Usage|null $var)
    {
        $this->usage = $var;

        return $this;
    }

}

