<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeReply</code>
 */
class GenerativeReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string result = 1;</code>
     */
    protected $result = '';
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeDebug debug = 2;</code>
     */
    protected $debug = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetadata metadata = 3;</code>
     */
    protected $metadata = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $result
     *     @type \Weaviate\Client\Proto\V1\GenerativeDebug $debug
     *     @type \Weaviate\Client\Proto\V1\GenerativeMetadata $metadata
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string result = 1;</code>
     * @return string
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>string result = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setResult(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeDebug debug = 2;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeDebug|null
     */
    public function getDebug()
    {
        return $this->debug;
    }

    public function hasDebug()
    {
        return isset($this->debug);
    }

    public function clearDebug()
    {
        unset($this->debug);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeDebug debug = 2;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeDebug $var
     * @return $this
     */
    public function setDebug(\Weaviate\Client\Proto\V1\GenerativeDebug|null $var)
    {
        $this->debug = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetadata metadata = 3;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeMetadata|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeMetadata metadata = 3;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeMetadata $var
     * @return $this
     */
    public function setMetadata(\Weaviate\Client\Proto\V1\GenerativeMetadata|null $var)
    {
        $this->metadata = $var;

        return $this;
    }

}

