<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeOllama</code>
 */
class GenerativeOllama extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string api_endpoint = 1;</code>
     */
    protected $api_endpoint = null;
    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     */
    protected $model = null;
    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     */
    protected $temperature = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 4;</code>
     */
    protected $images = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 5;</code>
     */
    protected $image_properties = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $api_endpoint
     *     @type string $model
     *     @type float $temperature
     *     @type \Weaviate\Client\Proto\V1\TextArray $images
     *     @type \Weaviate\Client\Proto\V1\TextArray $image_properties
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string api_endpoint = 1;</code>
     * @return string
     */
    public function getApiEndpoint()
    {
        return isset($this->api_endpoint) ? $this->api_endpoint : '';
    }

    public function hasApiEndpoint()
    {
        return isset($this->api_endpoint);
    }

    public function clearApiEndpoint()
    {
        unset($this->api_endpoint);
    }

    /**
     * Generated from protobuf field <code>optional string api_endpoint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApiEndpoint(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->api_endpoint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Generated from protobuf field <code>optional string model = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModel(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->model = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     * @return float
     */
    public function getTemperature()
    {
        return isset($this->temperature) ? $this->temperature : 0.0;
    }

    public function hasTemperature()
    {
        return isset($this->temperature);
    }

    public function clearTemperature()
    {
        unset($this->temperature);
    }

    /**
     * Generated from protobuf field <code>optional double temperature = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setTemperature(float $var)
    {
        $this->temperature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 4;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImages()
    {
        return $this->images;
    }

    public function hasImages()
    {
        return isset($this->images);
    }

    public function clearImages()
    {
        unset($this->images);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray images = 4;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImages(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->images = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 5;</code>
     * @return \Weaviate\Client\Proto\V1\TextArray|null
     */
    public function getImageProperties()
    {
        return $this->image_properties;
    }

    public function hasImageProperties()
    {
        return isset($this->image_properties);
    }

    public function clearImageProperties()
    {
        unset($this->image_properties);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.TextArray image_properties = 5;</code>
     * @param \Weaviate\Client\Proto\V1\TextArray $var
     * @return $this
     */
    public function setImageProperties(\Weaviate\Client\Proto\V1\TextArray|null $var)
    {
        $this->image_properties = $var;

        return $this;
    }

}

