<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GeoCoordinatesFilter</code>
 */
class GeoCoordinatesFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     */
    protected $latitude = 0.0;
    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>float distance = 3;</code>
     */
    protected $distance = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *     @type float $longitude
     *     @type float $distance
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude(float $var)
    {
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude(float $var)
    {
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float distance = 3;</code>
     * @return float
     */
    public function getDistance()
    {
        return $this->distance;
    }

    /**
     * Generated from protobuf field <code>float distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance(float $var)
    {
        $this->distance = $var;

        return $this;
    }

}

