<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GroupByResult</code>
 */
class GroupByResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>float min_distance = 2;</code>
     */
    protected $min_distance = 0.0;
    /**
     * Generated from protobuf field <code>float max_distance = 3;</code>
     */
    protected $max_distance = 0.0;
    /**
     * Generated from protobuf field <code>int64 number_of_objects = 4;</code>
     */
    protected $number_of_objects = 0;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult objects = 5;</code>
     */
    private $objects;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.RerankReply rerank = 6;</code>
     */
    protected $rerank = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeReply generative = 7 [deprecated = true];</code>
     * @deprecated
     */
    protected $generative = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_result = 8;</code>
     */
    protected $generative_result = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type float $min_distance
     *     @type float $max_distance
     *     @type int|string $number_of_objects
     *     @type \Weaviate\Client\Proto\V1\SearchResult[] $objects
     *     @type \Weaviate\Client\Proto\V1\RerankReply $rerank
     *     @type \Weaviate\Client\Proto\V1\GenerativeReply $generative
     *     @type \Weaviate\Client\Proto\V1\GenerativeResult $generative_result
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float min_distance = 2;</code>
     * @return float
     */
    public function getMinDistance()
    {
        return $this->min_distance;
    }

    /**
     * Generated from protobuf field <code>float min_distance = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMinDistance(float $var)
    {
        $this->min_distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_distance = 3;</code>
     * @return float
     */
    public function getMaxDistance()
    {
        return $this->max_distance;
    }

    /**
     * Generated from protobuf field <code>float max_distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxDistance(float $var)
    {
        $this->max_distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 number_of_objects = 4;</code>
     * @return int|string
     */
    public function getNumberOfObjects()
    {
        return $this->number_of_objects;
    }

    /**
     * Generated from protobuf field <code>int64 number_of_objects = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNumberOfObjects(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->number_of_objects = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult objects = 5;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\SearchResult>
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult objects = 5;</code>
     * @param \Weaviate\Client\Proto\V1\SearchResult[] $var
     * @return $this
     */
    public function setObjects(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\SearchResult::class);
        $this->objects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.RerankReply rerank = 6;</code>
     * @return \Weaviate\Client\Proto\V1\RerankReply|null
     */
    public function getRerank()
    {
        return $this->rerank;
    }

    public function hasRerank()
    {
        return isset($this->rerank);
    }

    public function clearRerank()
    {
        unset($this->rerank);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.RerankReply rerank = 6;</code>
     * @param \Weaviate\Client\Proto\V1\RerankReply $var
     * @return $this
     */
    public function setRerank(\Weaviate\Client\Proto\V1\RerankReply|null $var)
    {
        $this->rerank = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeReply generative = 7 [deprecated = true];</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeReply|null
     * @deprecated
     */
    public function getGenerative()
    {
        if (isset($this->generative)) {
            @trigger_error('generative is deprecated.', E_USER_DEPRECATED);
        }
        return $this->generative;
    }

    public function hasGenerative()
    {
        if (isset($this->generative)) {
            @trigger_error('generative is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->generative);
    }

    public function clearGenerative()
    {
        @trigger_error('generative is deprecated.', E_USER_DEPRECATED);
        unset($this->generative);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeReply generative = 7 [deprecated = true];</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeReply $var
     * @return $this
     * @deprecated
     */
    public function setGenerative(\Weaviate\Client\Proto\V1\GenerativeReply|null $var)
    {
        @trigger_error('generative is deprecated.', E_USER_DEPRECATED);
        $this->generative = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_result = 8;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeResult|null
     */
    public function getGenerativeResult()
    {
        return $this->generative_result;
    }

    public function hasGenerativeResult()
    {
        return isset($this->generative_result);
    }

    public function clearGenerativeResult()
    {
        unset($this->generative_result);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_result = 8;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeResult $var
     * @return $this
     */
    public function setGenerativeResult(\Weaviate\Client\Proto\V1\GenerativeResult|null $var)
    {
        $this->generative_result = $var;

        return $this;
    }

}

