<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GroupBy</code>
 */
class GroupBy extends \Google\Protobuf\Internal\Message
{
    /**
     * currently only supports one entry (eg just properties, no refs). But might
     * be extended in the future.
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     */
    private $path;
    /**
     * Generated from protobuf field <code>int32 number_of_groups = 2;</code>
     */
    protected $number_of_groups = 0;
    /**
     * Generated from protobuf field <code>int32 objects_per_group = 3;</code>
     */
    protected $objects_per_group = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $path
     *           currently only supports one entry (eg just properties, no refs). But might
     *           be extended in the future.
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type int $number_of_groups
     *     @type int $objects_per_group
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * currently only supports one entry (eg just properties, no refs). But might
     * be extended in the future.
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     * @return RepeatedField<string>
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * currently only supports one entry (eg just properties, no refs). But might
     * be extended in the future.
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string path = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPath(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->path = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 number_of_groups = 2;</code>
     * @return int
     */
    public function getNumberOfGroups()
    {
        return $this->number_of_groups;
    }

    /**
     * Generated from protobuf field <code>int32 number_of_groups = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumberOfGroups(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->number_of_groups = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 objects_per_group = 3;</code>
     * @return int
     */
    public function getObjectsPerGroup()
    {
        return $this->objects_per_group;
    }

    /**
     * Generated from protobuf field <code>int32 objects_per_group = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setObjectsPerGroup(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->objects_per_group = $var;

        return $this;
    }

}

