<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Hybrid</code>
 */
class Hybrid extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string query = 1;</code>
     */
    protected $query = '';
    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     */
    private $properties;
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 3 [deprecated = true];</code>
     * @deprecated
     */
    private $vector;
    /**
     * deprecated in 1.36.0 - use alpha_param
     *
     * Generated from protobuf field <code>float alpha = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $alpha = 0.0;
    /**
     * Generated from protobuf field <code>.weaviate.v1.Hybrid.FusionType fusion_type = 5;</code>
     */
    protected $fusion_type = 0;
    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 6 [deprecated = true];</code>
     * @deprecated
     */
    protected $vector_bytes = '';
    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 7 [deprecated = true];</code>
     * @deprecated
     */
    private $target_vectors;
    /**
     * targets in msg is ignored and should not be set for hybrid
     *
     * Generated from protobuf field <code>.weaviate.v1.NearTextSearch near_text = 8;</code>
     */
    protected $near_text = null;
    /**
     * same as above. Use the target vector in the hybrid message
     *
     * Generated from protobuf field <code>.weaviate.v1.NearVector near_vector = 9;</code>
     */
    protected $near_vector = null;
    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 10;</code>
     */
    protected $targets = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions bm25_search_operator = 11;</code>
     */
    protected $bm25_search_operator = null;
    /**
     * Generated from protobuf field <code>optional float alpha_param = 12;</code>
     */
    protected $alpha_param = null;
    /**
     * if true, alpha_param is used instead of alpha.
     * This is for backward compatibility, as alpha was used before alpha_param was introduced.
     *
     * Generated from protobuf field <code>bool use_alpha_param = 13;</code>
     */
    protected $use_alpha_param = false;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 14;</code>
     */
    protected $selection = null;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 21;</code>
     */
    private $vectors;
    protected $threshold;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $query
     *     @type string[] $properties
     *     @type float[] $vector
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type float $alpha
     *           deprecated in 1.36.0 - use alpha_param
     *     @type int $fusion_type
     *     @type string $vector_bytes
     *           deprecated in 1.29.0 - use vectors
     *     @type string[] $target_vectors
     *           deprecated in 1.26 - use targets
     *     @type \Weaviate\Client\Proto\V1\NearTextSearch $near_text
     *           targets in msg is ignored and should not be set for hybrid
     *     @type \Weaviate\Client\Proto\V1\NearVector $near_vector
     *           same as above. Use the target vector in the hybrid message
     *     @type \Weaviate\Client\Proto\V1\Targets $targets
     *     @type \Weaviate\Client\Proto\V1\SearchOperatorOptions $bm25_search_operator
     *     @type float $alpha_param
     *     @type bool $use_alpha_param
     *           if true, alpha_param is used instead of alpha.
     *           This is for backward compatibility, as alpha was used before alpha_param was introduced.
     *     @type \Weaviate\Client\Proto\V1\Selection $selection
     *     @type float $vector_distance
     *     @type \Weaviate\Client\Proto\V1\Vectors[] $vectors
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @return string
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * Generated from protobuf field <code>string query = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->query = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     * @return RepeatedField<string>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated string properties = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->properties = $arr;

        return $this;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 3 [deprecated = true];</code>
     * @return RepeatedField<float>
     * @deprecated
     */
    public function getVector()
    {
        if (count($this->vector) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 3 [deprecated = true];</code>
     * @param float[] $var
     * @return $this
     * @deprecated
     */
    public function setVector(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        if (count($arr) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        $this->vector = $arr;

        return $this;
    }

    /**
     * deprecated in 1.36.0 - use alpha_param
     *
     * Generated from protobuf field <code>float alpha = 4 [deprecated = true];</code>
     * @return float
     * @deprecated
     */
    public function getAlpha()
    {
        if ($this->alpha !== 0.0) {
            @trigger_error('alpha is deprecated.', E_USER_DEPRECATED);
        }
        return $this->alpha;
    }

    /**
     * deprecated in 1.36.0 - use alpha_param
     *
     * Generated from protobuf field <code>float alpha = 4 [deprecated = true];</code>
     * @param float $var
     * @return $this
     * @deprecated
     */
    public function setAlpha(float $var)
    {
        @trigger_error('alpha is deprecated.', E_USER_DEPRECATED);
        $this->alpha = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Hybrid.FusionType fusion_type = 5;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\Hybrid\FusionType}
     */
    public function getFusionType()
    {
        return $this->fusion_type;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Hybrid.FusionType fusion_type = 5;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\Hybrid\FusionType}
     * @return $this
     */
    public function setFusionType(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\Hybrid\FusionType::class);
        $this->fusion_type = $var;

        return $this;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 6 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getVectorBytes()
    {
        if ($this->vector_bytes !== '') {
            @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector_bytes;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 6 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setVectorBytes(string $var)
    {
        @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, false);
        $this->vector_bytes = $var;

        return $this;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 7 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getTargetVectors()
    {
        if (count($this->target_vectors) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        return $this->target_vectors;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 7 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setTargetVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        $this->target_vectors = $arr;

        return $this;
    }

    /**
     * targets in msg is ignored and should not be set for hybrid
     *
     * Generated from protobuf field <code>.weaviate.v1.NearTextSearch near_text = 8;</code>
     * @return \Weaviate\Client\Proto\V1\NearTextSearch|null
     */
    public function getNearText()
    {
        return $this->near_text;
    }

    public function hasNearText()
    {
        return isset($this->near_text);
    }

    public function clearNearText()
    {
        unset($this->near_text);
    }

    /**
     * targets in msg is ignored and should not be set for hybrid
     *
     * Generated from protobuf field <code>.weaviate.v1.NearTextSearch near_text = 8;</code>
     * @param \Weaviate\Client\Proto\V1\NearTextSearch $var
     * @return $this
     */
    public function setNearText(\Weaviate\Client\Proto\V1\NearTextSearch|null $var)
    {
        $this->near_text = $var;

        return $this;
    }

    /**
     * same as above. Use the target vector in the hybrid message
     *
     * Generated from protobuf field <code>.weaviate.v1.NearVector near_vector = 9;</code>
     * @return \Weaviate\Client\Proto\V1\NearVector|null
     */
    public function getNearVector()
    {
        return $this->near_vector;
    }

    public function hasNearVector()
    {
        return isset($this->near_vector);
    }

    public function clearNearVector()
    {
        unset($this->near_vector);
    }

    /**
     * same as above. Use the target vector in the hybrid message
     *
     * Generated from protobuf field <code>.weaviate.v1.NearVector near_vector = 9;</code>
     * @param \Weaviate\Client\Proto\V1\NearVector $var
     * @return $this
     */
    public function setNearVector(\Weaviate\Client\Proto\V1\NearVector|null $var)
    {
        $this->near_vector = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 10;</code>
     * @return \Weaviate\Client\Proto\V1\Targets|null
     */
    public function getTargets()
    {
        return $this->targets;
    }

    public function hasTargets()
    {
        return isset($this->targets);
    }

    public function clearTargets()
    {
        unset($this->targets);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 10;</code>
     * @param \Weaviate\Client\Proto\V1\Targets $var
     * @return $this
     */
    public function setTargets(\Weaviate\Client\Proto\V1\Targets|null $var)
    {
        $this->targets = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions bm25_search_operator = 11;</code>
     * @return \Weaviate\Client\Proto\V1\SearchOperatorOptions|null
     */
    public function getBm25SearchOperator()
    {
        return $this->bm25_search_operator;
    }

    public function hasBm25SearchOperator()
    {
        return isset($this->bm25_search_operator);
    }

    public function clearBm25SearchOperator()
    {
        unset($this->bm25_search_operator);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.SearchOperatorOptions bm25_search_operator = 11;</code>
     * @param \Weaviate\Client\Proto\V1\SearchOperatorOptions $var
     * @return $this
     */
    public function setBm25SearchOperator(\Weaviate\Client\Proto\V1\SearchOperatorOptions|null $var)
    {
        $this->bm25_search_operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional float alpha_param = 12;</code>
     * @return float
     */
    public function getAlphaParam()
    {
        return isset($this->alpha_param) ? $this->alpha_param : 0.0;
    }

    public function hasAlphaParam()
    {
        return isset($this->alpha_param);
    }

    public function clearAlphaParam()
    {
        unset($this->alpha_param);
    }

    /**
     * Generated from protobuf field <code>optional float alpha_param = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setAlphaParam(float $var)
    {
        $this->alpha_param = $var;

        return $this;
    }

    /**
     * if true, alpha_param is used instead of alpha.
     * This is for backward compatibility, as alpha was used before alpha_param was introduced.
     *
     * Generated from protobuf field <code>bool use_alpha_param = 13;</code>
     * @return bool
     */
    public function getUseAlphaParam()
    {
        return $this->use_alpha_param;
    }

    /**
     * if true, alpha_param is used instead of alpha.
     * This is for backward compatibility, as alpha was used before alpha_param was introduced.
     *
     * Generated from protobuf field <code>bool use_alpha_param = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseAlphaParam(bool $var)
    {
        $this->use_alpha_param = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 14;</code>
     * @return \Weaviate\Client\Proto\V1\Selection|null
     */
    public function getSelection()
    {
        return $this->selection;
    }

    public function hasSelection()
    {
        return isset($this->selection);
    }

    public function clearSelection()
    {
        unset($this->selection);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 14;</code>
     * @param \Weaviate\Client\Proto\V1\Selection $var
     * @return $this
     */
    public function setSelection(\Weaviate\Client\Proto\V1\Selection|null $var)
    {
        $this->selection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float vector_distance = 20;</code>
     * @return float
     */
    public function getVectorDistance()
    {
        return $this->readOneof(20);
    }

    public function hasVectorDistance()
    {
        return $this->hasOneof(20);
    }

    /**
     * Generated from protobuf field <code>float vector_distance = 20;</code>
     * @param float $var
     * @return $this
     */
    public function setVectorDistance(float $var)
    {
        $this->writeOneof(20, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 21;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Vectors>
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 21;</code>
     * @param \Weaviate\Client\Proto\V1\Vectors[] $var
     * @return $this
     */
    public function setVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Vectors::class);
        $this->vectors = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getThreshold()
    {
        return $this->whichOneof("threshold");
    }

}

