<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/properties.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.ListValue</code>
 */
class ListValue extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\NumberValues $number_values
     *     @type \Weaviate\Client\Proto\V1\BoolValues $bool_values
     *     @type \Weaviate\Client\Proto\V1\ObjectValues $object_values
     *     @type \Weaviate\Client\Proto\V1\DateValues $date_values
     *     @type \Weaviate\Client\Proto\V1\UuidValues $uuid_values
     *     @type \Weaviate\Client\Proto\V1\IntValues $int_values
     *     @type \Weaviate\Client\Proto\V1\TextValues $text_values
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Properties::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberValues number_values = 2;</code>
     * @return \Weaviate\Client\Proto\V1\NumberValues|null
     */
    public function getNumberValues()
    {
        return $this->readOneof(2);
    }

    public function hasNumberValues()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.NumberValues number_values = 2;</code>
     * @param \Weaviate\Client\Proto\V1\NumberValues $var
     * @return $this
     */
    public function setNumberValues(\Weaviate\Client\Proto\V1\NumberValues|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BoolValues bool_values = 3;</code>
     * @return \Weaviate\Client\Proto\V1\BoolValues|null
     */
    public function getBoolValues()
    {
        return $this->readOneof(3);
    }

    public function hasBoolValues()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.BoolValues bool_values = 3;</code>
     * @param \Weaviate\Client\Proto\V1\BoolValues $var
     * @return $this
     */
    public function setBoolValues(\Weaviate\Client\Proto\V1\BoolValues|null $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.ObjectValues object_values = 4;</code>
     * @return \Weaviate\Client\Proto\V1\ObjectValues|null
     */
    public function getObjectValues()
    {
        return $this->readOneof(4);
    }

    public function hasObjectValues()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.ObjectValues object_values = 4;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectValues $var
     * @return $this
     */
    public function setObjectValues(\Weaviate\Client\Proto\V1\ObjectValues|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.DateValues date_values = 5;</code>
     * @return \Weaviate\Client\Proto\V1\DateValues|null
     */
    public function getDateValues()
    {
        return $this->readOneof(5);
    }

    public function hasDateValues()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.DateValues date_values = 5;</code>
     * @param \Weaviate\Client\Proto\V1\DateValues $var
     * @return $this
     */
    public function setDateValues(\Weaviate\Client\Proto\V1\DateValues|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.UuidValues uuid_values = 6;</code>
     * @return \Weaviate\Client\Proto\V1\UuidValues|null
     */
    public function getUuidValues()
    {
        return $this->readOneof(6);
    }

    public function hasUuidValues()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.UuidValues uuid_values = 6;</code>
     * @param \Weaviate\Client\Proto\V1\UuidValues $var
     * @return $this
     */
    public function setUuidValues(\Weaviate\Client\Proto\V1\UuidValues|null $var)
    {
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntValues int_values = 7;</code>
     * @return \Weaviate\Client\Proto\V1\IntValues|null
     */
    public function getIntValues()
    {
        return $this->readOneof(7);
    }

    public function hasIntValues()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.IntValues int_values = 7;</code>
     * @param \Weaviate\Client\Proto\V1\IntValues $var
     * @return $this
     */
    public function setIntValues(\Weaviate\Client\Proto\V1\IntValues|null $var)
    {
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextValues text_values = 8;</code>
     * @return \Weaviate\Client\Proto\V1\TextValues|null
     */
    public function getTextValues()
    {
        return $this->readOneof(8);
    }

    public function hasTextValues()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TextValues text_values = 8;</code>
     * @param \Weaviate\Client\Proto\V1\TextValues $var
     * @return $this
     */
    public function setTextValues(\Weaviate\Client\Proto\V1\TextValues|null $var)
    {
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

