<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.NearTextSearch</code>
 */
class NearTextSearch extends \Google\Protobuf\Internal\Message
{
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string query = 1;</code>
     */
    private $query;
    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     */
    protected $certainty = null;
    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     */
    protected $distance = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_to = 4;</code>
     */
    protected $move_to = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_away = 5;</code>
     */
    protected $move_away = null;
    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 6 [deprecated = true];</code>
     * @deprecated
     */
    private $target_vectors;
    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 7;</code>
     */
    protected $targets = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 8;</code>
     */
    protected $selection = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $query
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type float $certainty
     *     @type float $distance
     *     @type \Weaviate\Client\Proto\V1\NearTextSearch\Move $move_to
     *     @type \Weaviate\Client\Proto\V1\NearTextSearch\Move $move_away
     *     @type string[] $target_vectors
     *           deprecated in 1.26 - use targets
     *     @type \Weaviate\Client\Proto\V1\Targets $targets
     *     @type \Weaviate\Client\Proto\V1\Selection $selection
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string query = 1;</code>
     * @return RepeatedField<string>
     */
    public function getQuery()
    {
        return $this->query;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated string query = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setQuery(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->query = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     * @return float
     */
    public function getCertainty()
    {
        return isset($this->certainty) ? $this->certainty : 0.0;
    }

    public function hasCertainty()
    {
        return isset($this->certainty);
    }

    public function clearCertainty()
    {
        unset($this->certainty);
    }

    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCertainty(float $var)
    {
        $this->certainty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @return float
     */
    public function getDistance()
    {
        return isset($this->distance) ? $this->distance : 0.0;
    }

    public function hasDistance()
    {
        return isset($this->distance);
    }

    public function clearDistance()
    {
        unset($this->distance);
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance(float $var)
    {
        $this->distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_to = 4;</code>
     * @return \Weaviate\Client\Proto\V1\NearTextSearch\Move|null
     */
    public function getMoveTo()
    {
        return $this->move_to;
    }

    public function hasMoveTo()
    {
        return isset($this->move_to);
    }

    public function clearMoveTo()
    {
        unset($this->move_to);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_to = 4;</code>
     * @param \Weaviate\Client\Proto\V1\NearTextSearch\Move $var
     * @return $this
     */
    public function setMoveTo(\Weaviate\Client\Proto\V1\NearTextSearch\Move|null $var)
    {
        $this->move_to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_away = 5;</code>
     * @return \Weaviate\Client\Proto\V1\NearTextSearch\Move|null
     */
    public function getMoveAway()
    {
        return $this->move_away;
    }

    public function hasMoveAway()
    {
        return isset($this->move_away);
    }

    public function clearMoveAway()
    {
        unset($this->move_away);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.NearTextSearch.Move move_away = 5;</code>
     * @param \Weaviate\Client\Proto\V1\NearTextSearch\Move $var
     * @return $this
     */
    public function setMoveAway(\Weaviate\Client\Proto\V1\NearTextSearch\Move|null $var)
    {
        $this->move_away = $var;

        return $this;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 6 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getTargetVectors()
    {
        if (count($this->target_vectors) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        return $this->target_vectors;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 6 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setTargetVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        $this->target_vectors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 7;</code>
     * @return \Weaviate\Client\Proto\V1\Targets|null
     */
    public function getTargets()
    {
        return $this->targets;
    }

    public function hasTargets()
    {
        return isset($this->targets);
    }

    public function clearTargets()
    {
        unset($this->targets);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 7;</code>
     * @param \Weaviate\Client\Proto\V1\Targets $var
     * @return $this
     */
    public function setTargets(\Weaviate\Client\Proto\V1\Targets|null $var)
    {
        $this->targets = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 8;</code>
     * @return \Weaviate\Client\Proto\V1\Selection|null
     */
    public function getSelection()
    {
        return $this->selection;
    }

    public function hasSelection()
    {
        return isset($this->selection);
    }

    public function clearSelection()
    {
        unset($this->selection);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 8;</code>
     * @param \Weaviate\Client\Proto\V1\Selection $var
     * @return $this
     */
    public function setSelection(\Weaviate\Client\Proto\V1\Selection|null $var)
    {
        $this->selection = $var;

        return $this;
    }

}

