<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.NearVector</code>
 */
class NearVector extends \Google\Protobuf\Internal\Message
{
    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 1 [deprecated = true];</code>
     * @deprecated
     */
    private $vector;
    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     */
    protected $certainty = null;
    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     */
    protected $distance = null;
    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $vector_bytes = '';
    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 5 [deprecated = true];</code>
     * @deprecated
     */
    private $target_vectors;
    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 6;</code>
     */
    protected $targets = null;
    /**
     * deprecated in 1.26.2 - use vector_for_targets
     *
     * Generated from protobuf field <code>map<string, bytes> vector_per_target = 7 [deprecated = true];</code>
     * @deprecated
     */
    private $vector_per_target;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.VectorForTarget vector_for_targets = 8;</code>
     */
    private $vector_for_targets;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 9;</code>
     */
    private $vectors;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 10;</code>
     */
    protected $selection = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[] $vector
     *           protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *     @type float $certainty
     *     @type float $distance
     *     @type string $vector_bytes
     *           deprecated in 1.29.0 - use vectors
     *     @type string[] $target_vectors
     *           deprecated in 1.26 - use targets
     *     @type \Weaviate\Client\Proto\V1\Targets $targets
     *     @type array|\Google\Protobuf\Internal\MapField $vector_per_target
     *           deprecated in 1.26.2 - use vector_for_targets
     *     @type \Weaviate\Client\Proto\V1\VectorForTarget[] $vector_for_targets
     *     @type \Weaviate\Client\Proto\V1\Vectors[] $vectors
     *     @type \Weaviate\Client\Proto\V1\Selection $selection
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 1 [deprecated = true];</code>
     * @return RepeatedField<float>
     * @deprecated
     */
    public function getVector()
    {
        if (count($this->vector) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector;
    }

    /**
     * protolint:disable:next REPEATED_FIELD_NAMES_PLURALIZED
     *
     * Generated from protobuf field <code>repeated float vector = 1 [deprecated = true];</code>
     * @param float[] $var
     * @return $this
     * @deprecated
     */
    public function setVector(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        if (count($arr) !== 0) {
            @trigger_error('vector is deprecated.', E_USER_DEPRECATED);
        }
        $this->vector = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     * @return float
     */
    public function getCertainty()
    {
        return isset($this->certainty) ? $this->certainty : 0.0;
    }

    public function hasCertainty()
    {
        return isset($this->certainty);
    }

    public function clearCertainty()
    {
        unset($this->certainty);
    }

    /**
     * Generated from protobuf field <code>optional double certainty = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setCertainty(float $var)
    {
        $this->certainty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @return float
     */
    public function getDistance()
    {
        return isset($this->distance) ? $this->distance : 0.0;
    }

    public function hasDistance()
    {
        return isset($this->distance);
    }

    public function clearDistance()
    {
        unset($this->distance);
    }

    /**
     * Generated from protobuf field <code>optional double distance = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistance(float $var)
    {
        $this->distance = $var;

        return $this;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 4 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getVectorBytes()
    {
        if ($this->vector_bytes !== '') {
            @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector_bytes;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 4 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setVectorBytes(string $var)
    {
        @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, false);
        $this->vector_bytes = $var;

        return $this;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 5 [deprecated = true];</code>
     * @return RepeatedField<string>
     * @deprecated
     */
    public function getTargetVectors()
    {
        if (count($this->target_vectors) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        return $this->target_vectors;
    }

    /**
     * deprecated in 1.26 - use targets
     *
     * Generated from protobuf field <code>repeated string target_vectors = 5 [deprecated = true];</code>
     * @param string[] $var
     * @return $this
     * @deprecated
     */
    public function setTargetVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        if (count($arr) !== 0) {
            @trigger_error('target_vectors is deprecated.', E_USER_DEPRECATED);
        }
        $this->target_vectors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 6;</code>
     * @return \Weaviate\Client\Proto\V1\Targets|null
     */
    public function getTargets()
    {
        return $this->targets;
    }

    public function hasTargets()
    {
        return isset($this->targets);
    }

    public function clearTargets()
    {
        unset($this->targets);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Targets targets = 6;</code>
     * @param \Weaviate\Client\Proto\V1\Targets $var
     * @return $this
     */
    public function setTargets(\Weaviate\Client\Proto\V1\Targets|null $var)
    {
        $this->targets = $var;

        return $this;
    }

    /**
     * deprecated in 1.26.2 - use vector_for_targets
     *
     * Generated from protobuf field <code>map<string, bytes> vector_per_target = 7 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\MapField
     * @deprecated
     */
    public function getVectorPerTarget()
    {
        if (count($this->vector_per_target) !== 0) {
            @trigger_error('vector_per_target is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector_per_target;
    }

    /**
     * deprecated in 1.26.2 - use vector_for_targets
     *
     * Generated from protobuf field <code>map<string, bytes> vector_per_target = 7 [deprecated = true];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     * @deprecated
     */
    public function setVectorPerTarget(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::BYTES);
        if (count($arr) !== 0) {
            @trigger_error('vector_per_target is deprecated.', E_USER_DEPRECATED);
        }
        $this->vector_per_target = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.VectorForTarget vector_for_targets = 8;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\VectorForTarget>
     */
    public function getVectorForTargets()
    {
        return $this->vector_for_targets;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.VectorForTarget vector_for_targets = 8;</code>
     * @param \Weaviate\Client\Proto\V1\VectorForTarget[] $var
     * @return $this
     */
    public function setVectorForTargets(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\VectorForTarget::class);
        $this->vector_for_targets = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 9;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Vectors>
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 9;</code>
     * @param \Weaviate\Client\Proto\V1\Vectors[] $var
     * @return $this
     */
    public function setVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Vectors::class);
        $this->vectors = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 10;</code>
     * @return \Weaviate\Client\Proto\V1\Selection|null
     */
    public function getSelection()
    {
        return $this->selection;
    }

    public function hasSelection()
    {
        return isset($this->selection);
    }

    public function clearSelection()
    {
        unset($this->selection);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.Selection selection = 10;</code>
     * @param \Weaviate\Client\Proto\V1\Selection $var
     * @return $this
     */
    public function setSelection(\Weaviate\Client\Proto\V1\Selection|null $var)
    {
        $this->selection = $var;

        return $this;
    }

}

