<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.NumberArrayProperties</code>
 */
class NumberArrayProperties extends \Google\Protobuf\Internal\Message
{
    /**
     * will be removed in the future, use vector_bytes
     * go client 5.4.1 depends on this field. Only remove after go client is deprecated
     *
     * Generated from protobuf field <code>repeated double values = 1 [deprecated = true];</code>
     * @deprecated
     */
    private $values;
    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     */
    protected $prop_name = '';
    /**
     * Generated from protobuf field <code>bytes values_bytes = 3;</code>
     */
    protected $values_bytes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[] $values
     *           will be removed in the future, use vector_bytes
     *           go client 5.4.1 depends on this field. Only remove after go client is deprecated
     *     @type string $prop_name
     *     @type string $values_bytes
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * will be removed in the future, use vector_bytes
     * go client 5.4.1 depends on this field. Only remove after go client is deprecated
     *
     * Generated from protobuf field <code>repeated double values = 1 [deprecated = true];</code>
     * @return RepeatedField<float>
     * @deprecated
     */
    public function getValues()
    {
        if (count($this->values) !== 0) {
            @trigger_error('values is deprecated.', E_USER_DEPRECATED);
        }
        return $this->values;
    }

    /**
     * will be removed in the future, use vector_bytes
     * go client 5.4.1 depends on this field. Only remove after go client is deprecated
     *
     * Generated from protobuf field <code>repeated double values = 1 [deprecated = true];</code>
     * @param float[] $var
     * @return $this
     * @deprecated
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        if (count($arr) !== 0) {
            @trigger_error('values is deprecated.', E_USER_DEPRECATED);
        }
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @return string
     */
    public function getPropName()
    {
        return $this->prop_name;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPropName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prop_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes values_bytes = 3;</code>
     * @return string
     */
    public function getValuesBytes()
    {
        return $this->values_bytes;
    }

    /**
     * Generated from protobuf field <code>bytes values_bytes = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setValuesBytes(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->values_bytes = $var;

        return $this;
    }

}

