<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.ObjectArrayProperties</code>
 */
class ObjectArrayProperties extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesValue values = 1;</code>
     */
    private $values;
    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     */
    protected $prop_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\ObjectPropertiesValue[] $values
     *     @type string $prop_name
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesValue values = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\ObjectPropertiesValue>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesValue values = 1;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectPropertiesValue[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\ObjectPropertiesValue::class);
        $this->values = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @return string
     */
    public function getPropName()
    {
        return $this->prop_name;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPropName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prop_name = $var;

        return $this;
    }

}

