<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/properties.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.ObjectValues</code>
 */
class ObjectValues extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Properties values = 1;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\Properties[] $values
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Properties::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Properties values = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Properties>
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Properties values = 1;</code>
     * @param \Weaviate\Client\Proto\V1\Properties[] $var
     * @return $this
     */
    public function setValues(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Properties::class);
        $this->values = $arr;

        return $this;
    }

}

