<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.ObjectPropertiesValue</code>
 */
class ObjectPropertiesValue extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct non_ref_properties = 1;</code>
     */
    protected $non_ref_properties = null;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.NumberArrayProperties number_array_properties = 2;</code>
     */
    private $number_array_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.IntArrayProperties int_array_properties = 3;</code>
     */
    private $int_array_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.TextArrayProperties text_array_properties = 4;</code>
     */
    private $text_array_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BooleanArrayProperties boolean_array_properties = 5;</code>
     */
    private $boolean_array_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectProperties object_properties = 6;</code>
     */
    private $object_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectArrayProperties object_array_properties = 7;</code>
     */
    private $object_array_properties;
    /**
     * Generated from protobuf field <code>repeated string empty_list_props = 10;</code>
     */
    private $empty_list_props;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $non_ref_properties
     *     @type \Weaviate\Client\Proto\V1\NumberArrayProperties[] $number_array_properties
     *     @type \Weaviate\Client\Proto\V1\IntArrayProperties[] $int_array_properties
     *     @type \Weaviate\Client\Proto\V1\TextArrayProperties[] $text_array_properties
     *     @type \Weaviate\Client\Proto\V1\BooleanArrayProperties[] $boolean_array_properties
     *     @type \Weaviate\Client\Proto\V1\ObjectProperties[] $object_properties
     *     @type \Weaviate\Client\Proto\V1\ObjectArrayProperties[] $object_array_properties
     *     @type string[] $empty_list_props
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct non_ref_properties = 1;</code>
     * @return \Google\Protobuf\Struct|null
     */
    public function getNonRefProperties()
    {
        return $this->non_ref_properties;
    }

    public function hasNonRefProperties()
    {
        return isset($this->non_ref_properties);
    }

    public function clearNonRefProperties()
    {
        unset($this->non_ref_properties);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct non_ref_properties = 1;</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setNonRefProperties(\Google\Protobuf\Struct|null $var)
    {
        $this->non_ref_properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.NumberArrayProperties number_array_properties = 2;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\NumberArrayProperties>
     */
    public function getNumberArrayProperties()
    {
        return $this->number_array_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.NumberArrayProperties number_array_properties = 2;</code>
     * @param \Weaviate\Client\Proto\V1\NumberArrayProperties[] $var
     * @return $this
     */
    public function setNumberArrayProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\NumberArrayProperties::class);
        $this->number_array_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.IntArrayProperties int_array_properties = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\IntArrayProperties>
     */
    public function getIntArrayProperties()
    {
        return $this->int_array_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.IntArrayProperties int_array_properties = 3;</code>
     * @param \Weaviate\Client\Proto\V1\IntArrayProperties[] $var
     * @return $this
     */
    public function setIntArrayProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\IntArrayProperties::class);
        $this->int_array_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.TextArrayProperties text_array_properties = 4;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\TextArrayProperties>
     */
    public function getTextArrayProperties()
    {
        return $this->text_array_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.TextArrayProperties text_array_properties = 4;</code>
     * @param \Weaviate\Client\Proto\V1\TextArrayProperties[] $var
     * @return $this
     */
    public function setTextArrayProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\TextArrayProperties::class);
        $this->text_array_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BooleanArrayProperties boolean_array_properties = 5;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\BooleanArrayProperties>
     */
    public function getBooleanArrayProperties()
    {
        return $this->boolean_array_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.BooleanArrayProperties boolean_array_properties = 5;</code>
     * @param \Weaviate\Client\Proto\V1\BooleanArrayProperties[] $var
     * @return $this
     */
    public function setBooleanArrayProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\BooleanArrayProperties::class);
        $this->boolean_array_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectProperties object_properties = 6;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\ObjectProperties>
     */
    public function getObjectProperties()
    {
        return $this->object_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectProperties object_properties = 6;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectProperties[] $var
     * @return $this
     */
    public function setObjectProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\ObjectProperties::class);
        $this->object_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectArrayProperties object_array_properties = 7;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\ObjectArrayProperties>
     */
    public function getObjectArrayProperties()
    {
        return $this->object_array_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectArrayProperties object_array_properties = 7;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectArrayProperties[] $var
     * @return $this
     */
    public function setObjectArrayProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\ObjectArrayProperties::class);
        $this->object_array_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string empty_list_props = 10;</code>
     * @return RepeatedField<string>
     */
    public function getEmptyListProps()
    {
        return $this->empty_list_props;
    }

    /**
     * Generated from protobuf field <code>repeated string empty_list_props = 10;</code>
     * @param string[] $var
     * @return $this
     */
    public function setEmptyListProps(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->empty_list_props = $arr;

        return $this;
    }

}

