<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.ObjectPropertiesRequest</code>
 */
class ObjectPropertiesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string prop_name = 1;</code>
     */
    protected $prop_name = '';
    /**
     * Generated from protobuf field <code>repeated string primitive_properties = 2;</code>
     */
    private $primitive_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     */
    private $object_properties;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $prop_name
     *     @type string[] $primitive_properties
     *     @type \Weaviate\Client\Proto\V1\ObjectPropertiesRequest[] $object_properties
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string prop_name = 1;</code>
     * @return string
     */
    public function getPropName()
    {
        return $this->prop_name;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPropName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prop_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string primitive_properties = 2;</code>
     * @return RepeatedField<string>
     */
    public function getPrimitiveProperties()
    {
        return $this->primitive_properties;
    }

    /**
     * Generated from protobuf field <code>repeated string primitive_properties = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setPrimitiveProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->primitive_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\ObjectPropertiesRequest>
     */
    public function getObjectProperties()
    {
        return $this->object_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectPropertiesRequest[] $var
     * @return $this
     */
    public function setObjectProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\ObjectPropertiesRequest::class);
        $this->object_properties = $arr;

        return $this;
    }

}

