<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.PropertiesRequest</code>
 */
class PropertiesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string non_ref_properties = 1;</code>
     */
    private $non_ref_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.RefPropertiesRequest ref_properties = 2;</code>
     */
    private $ref_properties;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     */
    private $object_properties;
    /**
     * Generated from protobuf field <code>bool return_all_nonref_properties = 11;</code>
     */
    protected $return_all_nonref_properties = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $non_ref_properties
     *     @type \Weaviate\Client\Proto\V1\RefPropertiesRequest[] $ref_properties
     *     @type \Weaviate\Client\Proto\V1\ObjectPropertiesRequest[] $object_properties
     *     @type bool $return_all_nonref_properties
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string non_ref_properties = 1;</code>
     * @return RepeatedField<string>
     */
    public function getNonRefProperties()
    {
        return $this->non_ref_properties;
    }

    /**
     * Generated from protobuf field <code>repeated string non_ref_properties = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setNonRefProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->non_ref_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.RefPropertiesRequest ref_properties = 2;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\RefPropertiesRequest>
     */
    public function getRefProperties()
    {
        return $this->ref_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.RefPropertiesRequest ref_properties = 2;</code>
     * @param \Weaviate\Client\Proto\V1\RefPropertiesRequest[] $var
     * @return $this
     */
    public function setRefProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\RefPropertiesRequest::class);
        $this->ref_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\ObjectPropertiesRequest>
     */
    public function getObjectProperties()
    {
        return $this->object_properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.ObjectPropertiesRequest object_properties = 3;</code>
     * @param \Weaviate\Client\Proto\V1\ObjectPropertiesRequest[] $var
     * @return $this
     */
    public function setObjectProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\ObjectPropertiesRequest::class);
        $this->object_properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool return_all_nonref_properties = 11;</code>
     * @return bool
     */
    public function getReturnAllNonrefProperties()
    {
        return $this->return_all_nonref_properties;
    }

    /**
     * Generated from protobuf field <code>bool return_all_nonref_properties = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnAllNonrefProperties(bool $var)
    {
        $this->return_all_nonref_properties = $var;

        return $this;
    }

}

