<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * QueryProfile contains per-shard profiling data for a search query.
 * Only populated when MetadataRequest.profile is true.
 *
 * Generated from protobuf message <code>weaviate.v1.QueryProfile</code>
 */
class QueryProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.QueryProfile.ShardProfile shards = 1;</code>
     */
    private $shards;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\QueryProfile\ShardProfile[] $shards
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.QueryProfile.ShardProfile shards = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\QueryProfile\ShardProfile>
     */
    public function getShards()
    {
        return $this->shards;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.QueryProfile.ShardProfile shards = 1;</code>
     * @param \Weaviate\Client\Proto\V1\QueryProfile\ShardProfile[] $var
     * @return $this
     */
    public function setShards(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\QueryProfile\ShardProfile::class);
        $this->shards = $arr;

        return $this;
    }

}

