<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.RefPropertiesResult</code>
 */
class RefPropertiesResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.PropertiesResult properties = 1;</code>
     */
    private $properties;
    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     */
    protected $prop_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\PropertiesResult[] $properties
     *     @type string $prop_name
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.PropertiesResult properties = 1;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\PropertiesResult>
     */
    public function getProperties()
    {
        return $this->properties;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.PropertiesResult properties = 1;</code>
     * @param \Weaviate\Client\Proto\V1\PropertiesResult[] $var
     * @return $this
     */
    public function setProperties(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\PropertiesResult::class);
        $this->properties = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @return string
     */
    public function getPropName()
    {
        return $this->prop_name;
    }

    /**
     * Generated from protobuf field <code>string prop_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPropName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->prop_name = $var;

        return $this;
    }

}

