<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.RefPropertiesRequest</code>
 */
class RefPropertiesRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string reference_property = 1;</code>
     */
    protected $reference_property = '';
    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesRequest properties = 2;</code>
     */
    protected $properties = null;
    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataRequest metadata = 3;</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>string target_collection = 4;</code>
     */
    protected $target_collection = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $reference_property
     *     @type \Weaviate\Client\Proto\V1\PropertiesRequest $properties
     *     @type \Weaviate\Client\Proto\V1\MetadataRequest $metadata
     *     @type string $target_collection
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string reference_property = 1;</code>
     * @return string
     */
    public function getReferenceProperty()
    {
        return $this->reference_property;
    }

    /**
     * Generated from protobuf field <code>string reference_property = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setReferenceProperty(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->reference_property = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesRequest properties = 2;</code>
     * @return \Weaviate\Client\Proto\V1\PropertiesRequest|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesRequest properties = 2;</code>
     * @param \Weaviate\Client\Proto\V1\PropertiesRequest $var
     * @return $this
     */
    public function setProperties(\Weaviate\Client\Proto\V1\PropertiesRequest|null $var)
    {
        $this->properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataRequest metadata = 3;</code>
     * @return \Weaviate\Client\Proto\V1\MetadataRequest|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataRequest metadata = 3;</code>
     * @param \Weaviate\Client\Proto\V1\MetadataRequest $var
     * @return $this
     */
    public function setMetadata(\Weaviate\Client\Proto\V1\MetadataRequest|null $var)
    {
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string target_collection = 4;</code>
     * @return string
     */
    public function getTargetCollection()
    {
        return $this->target_collection;
    }

    /**
     * Generated from protobuf field <code>string target_collection = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTargetCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target_collection = $var;

        return $this;
    }

}

