<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Rerank</code>
 */
class Rerank extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string property = 1;</code>
     */
    protected $property = '';
    /**
     * Generated from protobuf field <code>optional string query = 2;</code>
     */
    protected $query = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $property
     *     @type string $query
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @return string
     */
    public function getProperty()
    {
        return $this->property;
    }

    /**
     * Generated from protobuf field <code>string property = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setProperty(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->property = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string query = 2;</code>
     * @return string
     */
    public function getQuery()
    {
        return isset($this->query) ? $this->query : '';
    }

    public function hasQuery()
    {
        return isset($this->query);
    }

    public function clearQuery()
    {
        unset($this->query);
    }

    /**
     * Generated from protobuf field <code>optional string query = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setQuery(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->query = $var;

        return $this;
    }

}

