<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.SearchResult</code>
 */
class SearchResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesResult properties = 1;</code>
     */
    protected $properties = null;
    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataResult metadata = 2;</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative = 3;</code>
     */
    protected $generative = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Weaviate\Client\Proto\V1\PropertiesResult $properties
     *     @type \Weaviate\Client\Proto\V1\MetadataResult $metadata
     *     @type \Weaviate\Client\Proto\V1\GenerativeResult $generative
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesResult properties = 1;</code>
     * @return \Weaviate\Client\Proto\V1\PropertiesResult|null
     */
    public function getProperties()
    {
        return $this->properties;
    }

    public function hasProperties()
    {
        return isset($this->properties);
    }

    public function clearProperties()
    {
        unset($this->properties);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PropertiesResult properties = 1;</code>
     * @param \Weaviate\Client\Proto\V1\PropertiesResult $var
     * @return $this
     */
    public function setProperties(\Weaviate\Client\Proto\V1\PropertiesResult|null $var)
    {
        $this->properties = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataResult metadata = 2;</code>
     * @return \Weaviate\Client\Proto\V1\MetadataResult|null
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    public function hasMetadata()
    {
        return isset($this->metadata);
    }

    public function clearMetadata()
    {
        unset($this->metadata);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.MetadataResult metadata = 2;</code>
     * @param \Weaviate\Client\Proto\V1\MetadataResult $var
     * @return $this
     */
    public function setMetadata(\Weaviate\Client\Proto\V1\MetadataResult|null $var)
    {
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative = 3;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeResult|null
     */
    public function getGenerative()
    {
        return $this->generative;
    }

    public function hasGenerative()
    {
        return isset($this->generative);
    }

    public function clearGenerative()
    {
        unset($this->generative);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative = 3;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeResult $var
     * @return $this
     */
    public function setGenerative(\Weaviate\Client\Proto\V1\GenerativeResult|null $var)
    {
        $this->generative = $var;

        return $this;
    }

}

