<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.SearchOperatorOptions</code>
 */
class SearchOperatorOptions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.weaviate.v1.SearchOperatorOptions.Operator operator = 1;</code>
     */
    protected $operator = 0;
    /**
     * Generated from protobuf field <code>optional int32 minimum_or_tokens_match = 2;</code>
     */
    protected $minimum_or_tokens_match = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $operator
     *     @type int $minimum_or_tokens_match
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.SearchOperatorOptions.Operator operator = 1;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\SearchOperatorOptions\Operator}
     */
    public function getOperator()
    {
        return $this->operator;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.SearchOperatorOptions.Operator operator = 1;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\SearchOperatorOptions\Operator}
     * @return $this
     */
    public function setOperator(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\SearchOperatorOptions\Operator::class);
        $this->operator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 minimum_or_tokens_match = 2;</code>
     * @return int
     */
    public function getMinimumOrTokensMatch()
    {
        return isset($this->minimum_or_tokens_match) ? $this->minimum_or_tokens_match : 0;
    }

    public function hasMinimumOrTokensMatch()
    {
        return isset($this->minimum_or_tokens_match);
    }

    public function clearMinimumOrTokensMatch()
    {
        unset($this->minimum_or_tokens_match);
    }

    /**
     * Generated from protobuf field <code>optional int32 minimum_or_tokens_match = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMinimumOrTokensMatch(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->minimum_or_tokens_match = $var;

        return $this;
    }

}

