<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/search_get.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.SearchReply</code>
 */
class SearchReply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float took = 1;</code>
     */
    protected $took = 0.0;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult results = 2;</code>
     */
    private $results;
    /**
     * Generated from protobuf field <code>optional string generative_grouped_result = 3 [deprecated = true];</code>
     * @deprecated
     */
    protected $generative_grouped_result = null;
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.GroupByResult group_by_results = 4;</code>
     */
    private $group_by_results;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_grouped_results = 5;</code>
     */
    protected $generative_grouped_results = null;
    /**
     * Generated from protobuf field <code>optional .weaviate.v1.QueryProfile query_profile = 6;</code>
     */
    protected $query_profile = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $took
     *     @type \Weaviate\Client\Proto\V1\SearchResult[] $results
     *     @type string $generative_grouped_result
     *     @type \Weaviate\Client\Proto\V1\GroupByResult[] $group_by_results
     *     @type \Weaviate\Client\Proto\V1\GenerativeResult $generative_grouped_results
     *     @type \Weaviate\Client\Proto\V1\QueryProfile $query_profile
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\SearchGet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @return float
     */
    public function getTook()
    {
        return $this->took;
    }

    /**
     * Generated from protobuf field <code>float took = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setTook(float $var)
    {
        $this->took = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult results = 2;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\SearchResult>
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.SearchResult results = 2;</code>
     * @param \Weaviate\Client\Proto\V1\SearchResult[] $var
     * @return $this
     */
    public function setResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\SearchResult::class);
        $this->results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string generative_grouped_result = 3 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getGenerativeGroupedResult()
    {
        if (isset($this->generative_grouped_result)) {
            @trigger_error('generative_grouped_result is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->generative_grouped_result) ? $this->generative_grouped_result : '';
    }

    public function hasGenerativeGroupedResult()
    {
        if (isset($this->generative_grouped_result)) {
            @trigger_error('generative_grouped_result is deprecated.', E_USER_DEPRECATED);
        }
        return isset($this->generative_grouped_result);
    }

    public function clearGenerativeGroupedResult()
    {
        @trigger_error('generative_grouped_result is deprecated.', E_USER_DEPRECATED);
        unset($this->generative_grouped_result);
    }

    /**
     * Generated from protobuf field <code>optional string generative_grouped_result = 3 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setGenerativeGroupedResult(string $var)
    {
        @trigger_error('generative_grouped_result is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, true);
        $this->generative_grouped_result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.GroupByResult group_by_results = 4;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\GroupByResult>
     */
    public function getGroupByResults()
    {
        return $this->group_by_results;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.GroupByResult group_by_results = 4;</code>
     * @param \Weaviate\Client\Proto\V1\GroupByResult[] $var
     * @return $this
     */
    public function setGroupByResults(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\GroupByResult::class);
        $this->group_by_results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_grouped_results = 5;</code>
     * @return \Weaviate\Client\Proto\V1\GenerativeResult|null
     */
    public function getGenerativeGroupedResults()
    {
        return $this->generative_grouped_results;
    }

    public function hasGenerativeGroupedResults()
    {
        return isset($this->generative_grouped_results);
    }

    public function clearGenerativeGroupedResults()
    {
        unset($this->generative_grouped_results);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.GenerativeResult generative_grouped_results = 5;</code>
     * @param \Weaviate\Client\Proto\V1\GenerativeResult $var
     * @return $this
     */
    public function setGenerativeGroupedResults(\Weaviate\Client\Proto\V1\GenerativeResult|null $var)
    {
        $this->generative_grouped_results = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.QueryProfile query_profile = 6;</code>
     * @return \Weaviate\Client\Proto\V1\QueryProfile|null
     */
    public function getQueryProfile()
    {
        return $this->query_profile;
    }

    public function hasQueryProfile()
    {
        return isset($this->query_profile);
    }

    public function clearQueryProfile()
    {
        unset($this->query_profile);
    }

    /**
     * Generated from protobuf field <code>optional .weaviate.v1.QueryProfile query_profile = 6;</code>
     * @param \Weaviate\Client\Proto\V1\QueryProfile $var
     * @return $this
     */
    public function setQueryProfile(\Weaviate\Client\Proto\V1\QueryProfile|null $var)
    {
        $this->query_profile = $var;

        return $this;
    }

}

