<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/tenants.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.TenantsGetRequest</code>
 */
class TenantsGetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     */
    protected $collection = '';
    protected $params;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $collection
     *     @type \Weaviate\Client\Proto\V1\TenantNames $names
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Tenants::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @return string
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * Generated from protobuf field <code>string collection = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCollection(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->collection = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TenantNames names = 2;</code>
     * @return \Weaviate\Client\Proto\V1\TenantNames|null
     */
    public function getNames()
    {
        return $this->readOneof(2);
    }

    public function hasNames()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.TenantNames names = 2;</code>
     * @param \Weaviate\Client\Proto\V1\TenantNames $var
     * @return $this
     */
    public function setNames(\Weaviate\Client\Proto\V1\TenantNames|null $var)
    {
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getParams()
    {
        return $this->whichOneof("params");
    }

}

