<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/properties.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $kind;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $number_value
     *     @type bool $bool_value
     *          dont reuse 2, old field that has been removed; Was "string string_value = 2;"
     *     @type \Weaviate\Client\Proto\V1\Properties $object_value
     *     @type \Weaviate\Client\Proto\V1\ListValue $list_value
     *     @type string $date_value
     *     @type string $uuid_value
     *     @type int|string $int_value
     *     @type \Weaviate\Client\Proto\V1\GeoCoordinate $geo_value
     *     @type string $blob_value
     *     @type \Weaviate\Client\Proto\V1\PhoneNumber $phone_value
     *     @type int $null_value
     *     @type string $text_value
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Properties::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double number_value = 1;</code>
     * @return float
     */
    public function getNumberValue()
    {
        return $this->readOneof(1);
    }

    public function hasNumberValue()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>double number_value = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setNumberValue(float $var)
    {
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *dont reuse 2, old field that has been removed; Was "string string_value = 2;"
     *
     * Generated from protobuf field <code>bool bool_value = 3;</code>
     * @return bool
     */
    public function getBoolValue()
    {
        return $this->readOneof(3);
    }

    public function hasBoolValue()
    {
        return $this->hasOneof(3);
    }

    /**
     *dont reuse 2, old field that has been removed; Was "string string_value = 2;"
     *
     * Generated from protobuf field <code>bool bool_value = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolValue(bool $var)
    {
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Properties object_value = 4;</code>
     * @return \Weaviate\Client\Proto\V1\Properties|null
     */
    public function getObjectValue()
    {
        return $this->readOneof(4);
    }

    public function hasObjectValue()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Properties object_value = 4;</code>
     * @param \Weaviate\Client\Proto\V1\Properties $var
     * @return $this
     */
    public function setObjectValue(\Weaviate\Client\Proto\V1\Properties|null $var)
    {
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.ListValue list_value = 5;</code>
     * @return \Weaviate\Client\Proto\V1\ListValue|null
     */
    public function getListValue()
    {
        return $this->readOneof(5);
    }

    public function hasListValue()
    {
        return $this->hasOneof(5);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.ListValue list_value = 5;</code>
     * @param \Weaviate\Client\Proto\V1\ListValue $var
     * @return $this
     */
    public function setListValue(\Weaviate\Client\Proto\V1\ListValue|null $var)
    {
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string date_value = 6;</code>
     * @return string
     */
    public function getDateValue()
    {
        return $this->readOneof(6);
    }

    public function hasDateValue()
    {
        return $this->hasOneof(6);
    }

    /**
     * Generated from protobuf field <code>string date_value = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDateValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(6, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string uuid_value = 7;</code>
     * @return string
     */
    public function getUuidValue()
    {
        return $this->readOneof(7);
    }

    public function hasUuidValue()
    {
        return $this->hasOneof(7);
    }

    /**
     * Generated from protobuf field <code>string uuid_value = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setUuidValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(7, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 8;</code>
     * @return int|string
     */
    public function getIntValue()
    {
        return $this->readOneof(8);
    }

    public function hasIntValue()
    {
        return $this->hasOneof(8);
    }

    /**
     * Generated from protobuf field <code>int64 int_value = 8;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIntValue(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(8, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinate geo_value = 9;</code>
     * @return \Weaviate\Client\Proto\V1\GeoCoordinate|null
     */
    public function getGeoValue()
    {
        return $this->readOneof(9);
    }

    public function hasGeoValue()
    {
        return $this->hasOneof(9);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.GeoCoordinate geo_value = 9;</code>
     * @param \Weaviate\Client\Proto\V1\GeoCoordinate $var
     * @return $this
     */
    public function setGeoValue(\Weaviate\Client\Proto\V1\GeoCoordinate|null $var)
    {
        $this->writeOneof(9, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string blob_value = 10;</code>
     * @return string
     */
    public function getBlobValue()
    {
        return $this->readOneof(10);
    }

    public function hasBlobValue()
    {
        return $this->hasOneof(10);
    }

    /**
     * Generated from protobuf field <code>string blob_value = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBlobValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(10, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PhoneNumber phone_value = 11;</code>
     * @return \Weaviate\Client\Proto\V1\PhoneNumber|null
     */
    public function getPhoneValue()
    {
        return $this->readOneof(11);
    }

    public function hasPhoneValue()
    {
        return $this->hasOneof(11);
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.PhoneNumber phone_value = 11;</code>
     * @param \Weaviate\Client\Proto\V1\PhoneNumber $var
     * @return $this
     */
    public function setPhoneValue(\Weaviate\Client\Proto\V1\PhoneNumber|null $var)
    {
        $this->writeOneof(11, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.NullValue null_value = 12;</code>
     * @return int one of the values in {@see \Google\Protobuf\NullValue}
     */
    public function getNullValue()
    {
        return $this->readOneof(12);
    }

    public function hasNullValue()
    {
        return $this->hasOneof(12);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.NullValue null_value = 12;</code>
     * @param int $var one of the values in {@see \Google\Protobuf\NullValue}
     * @return $this
     */
    public function setNullValue(int $var)
    {
        GPBUtil::checkEnum($var, \Google\Protobuf\NullValue::class);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text_value = 13;</code>
     * @return string
     */
    public function getTextValue()
    {
        return $this->readOneof(13);
    }

    public function hasTextValue()
    {
        return $this->hasOneof(13);
    }

    /**
     * Generated from protobuf field <code>string text_value = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setTextValue(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->writeOneof(13, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getKind()
    {
        return $this->whichOneof("kind");
    }

}

