<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.Vectors</code>
 */
class Vectors extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * for multi-vec
     *
     * Generated from protobuf field <code>uint64 index = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $index = 0;
    /**
     * Generated from protobuf field <code>bytes vector_bytes = 3;</code>
     */
    protected $vector_bytes = '';
    /**
     * Generated from protobuf field <code>.weaviate.v1.Vectors.VectorType type = 4;</code>
     */
    protected $type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int|string $index
     *           for multi-vec
     *     @type string $vector_bytes
     *     @type int $type
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * for multi-vec
     *
     * Generated from protobuf field <code>uint64 index = 2 [deprecated = true];</code>
     * @return int|string
     * @deprecated
     */
    public function getIndex()
    {
        if ($this->index !== 0) {
            @trigger_error('index is deprecated.', E_USER_DEPRECATED);
        }
        return $this->index;
    }

    /**
     * for multi-vec
     *
     * Generated from protobuf field <code>uint64 index = 2 [deprecated = true];</code>
     * @param int|string $var
     * @return $this
     * @deprecated
     */
    public function setIndex(int|string $var)
    {
        @trigger_error('index is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint64($var);
        $this->index = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes vector_bytes = 3;</code>
     * @return string
     */
    public function getVectorBytes()
    {
        return $this->vector_bytes;
    }

    /**
     * Generated from protobuf field <code>bytes vector_bytes = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVectorBytes(string $var)
    {
        GPBUtil::checkString($var, false);
        $this->vector_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Vectors.VectorType type = 4;</code>
     * @return int one of the values in {@see \Weaviate\Client\Proto\V1\Vectors\VectorType}
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.weaviate.v1.Vectors.VectorType type = 4;</code>
     * @param int $var one of the values in {@see \Weaviate\Client\Proto\V1\Vectors\VectorType}
     * @return $this
     */
    public function setType(int $var)
    {
        GPBUtil::checkEnum($var, \Weaviate\Client\Proto\V1\Vectors\VectorType::class);
        $this->type = $var;

        return $this;
    }

}

