<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.VectorForTarget</code>
 */
class VectorForTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 2 [deprecated = true];</code>
     * @deprecated
     */
    protected $vector_bytes = '';
    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 3;</code>
     */
    private $vectors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $vector_bytes
     *           deprecated in 1.29.0 - use vectors
     *     @type \Weaviate\Client\Proto\V1\Vectors[] $vectors
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 2 [deprecated = true];</code>
     * @return string
     * @deprecated
     */
    public function getVectorBytes()
    {
        if ($this->vector_bytes !== '') {
            @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        }
        return $this->vector_bytes;
    }

    /**
     * deprecated in 1.29.0 - use vectors
     *
     * Generated from protobuf field <code>bytes vector_bytes = 2 [deprecated = true];</code>
     * @param string $var
     * @return $this
     * @deprecated
     */
    public function setVectorBytes(string $var)
    {
        @trigger_error('vector_bytes is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkString($var, false);
        $this->vector_bytes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 3;</code>
     * @return RepeatedField<\Weaviate\Client\Proto\V1\Vectors>
     */
    public function getVectors()
    {
        return $this->vectors;
    }

    /**
     * Generated from protobuf field <code>repeated .weaviate.v1.Vectors vectors = 3;</code>
     * @param \Weaviate\Client\Proto\V1\Vectors[] $var
     * @return $this
     */
    public function setVectors(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Weaviate\Client\Proto\V1\Vectors::class);
        $this->vectors = $arr;

        return $this;
    }

}

