<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/base_search.proto

namespace Weaviate\Client\Proto\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.WeightsForTarget</code>
 */
class WeightsForTarget extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string target = 1;</code>
     */
    protected $target = '';
    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     */
    protected $weight = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $target
     *     @type float $weight
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\BaseSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string target = 1;</code>
     * @return string
     */
    public function getTarget()
    {
        return $this->target;
    }

    /**
     * Generated from protobuf field <code>string target = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTarget(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->target = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     * @return float
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Generated from protobuf field <code>float weight = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setWeight(float $var)
    {
        $this->weight = $var;

        return $this;
    }

}

