<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeMeta;

use UnexpectedValueException;

/**
 * Protobuf type <code>weaviate.v1.GenerativeMeta.ReasoningEffort</code>
 */
class ReasoningEffort
{
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_UNSPECIFIED = 0;</code>
     */
    const REASONING_EFFORT_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_NONE = 1;</code>
     */
    const REASONING_EFFORT_NONE = 1;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_MINIMAL = 2;</code>
     */
    const REASONING_EFFORT_MINIMAL = 2;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_LOW = 3;</code>
     */
    const REASONING_EFFORT_LOW = 3;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_MEDIUM = 4;</code>
     */
    const REASONING_EFFORT_MEDIUM = 4;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_HIGH = 5;</code>
     */
    const REASONING_EFFORT_HIGH = 5;
    /**
     * Generated from protobuf enum <code>REASONING_EFFORT_XHIGH = 6;</code>
     */
    const REASONING_EFFORT_XHIGH = 6;

    private static $valueToName = [
        self::REASONING_EFFORT_UNSPECIFIED => 'REASONING_EFFORT_UNSPECIFIED',
        self::REASONING_EFFORT_NONE => 'REASONING_EFFORT_NONE',
        self::REASONING_EFFORT_MINIMAL => 'REASONING_EFFORT_MINIMAL',
        self::REASONING_EFFORT_LOW => 'REASONING_EFFORT_LOW',
        self::REASONING_EFFORT_MEDIUM => 'REASONING_EFFORT_MEDIUM',
        self::REASONING_EFFORT_HIGH => 'REASONING_EFFORT_HIGH',
        self::REASONING_EFFORT_XHIGH => 'REASONING_EFFORT_XHIGH',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

