<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeGoogleMetadata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeGoogleMetadata.TokenCount</code>
 */
class TokenCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 total_billable_characters = 1;</code>
     */
    protected $total_billable_characters = null;
    /**
     * Generated from protobuf field <code>optional int64 total_tokens = 2;</code>
     */
    protected $total_tokens = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $total_billable_characters
     *     @type int|string $total_tokens
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_billable_characters = 1;</code>
     * @return int|string
     */
    public function getTotalBillableCharacters()
    {
        return isset($this->total_billable_characters) ? $this->total_billable_characters : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasTotalBillableCharacters()
    {
        return isset($this->total_billable_characters);
    }

    public function clearTotalBillableCharacters()
    {
        unset($this->total_billable_characters);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_billable_characters = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalBillableCharacters(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->total_billable_characters = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 total_tokens = 2;</code>
     * @return int|string
     */
    public function getTotalTokens()
    {
        return isset($this->total_tokens) ? $this->total_tokens : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasTotalTokens()
    {
        return isset($this->total_tokens);
    }

    public function clearTotalTokens()
    {
        unset($this->total_tokens);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_tokens = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalTokens(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->total_tokens = $var;

        return $this;
    }

}

