<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/generative.proto

namespace Weaviate\Client\Proto\V1\GenerativeGoogleMetadata;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>weaviate.v1.GenerativeGoogleMetadata.UsageMetadata</code>
 */
class UsageMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional int64 prompt_token_count = 1;</code>
     */
    protected $prompt_token_count = null;
    /**
     * Generated from protobuf field <code>optional int64 candidates_token_count = 2;</code>
     */
    protected $candidates_token_count = null;
    /**
     * Generated from protobuf field <code>optional int64 total_token_count = 3;</code>
     */
    protected $total_token_count = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $prompt_token_count
     *     @type int|string $candidates_token_count
     *     @type int|string $total_token_count
     * }
     */
    public function __construct($data = NULL) {
        \Weaviate\Client\Proto\GPBMetadata\V1\Generative::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional int64 prompt_token_count = 1;</code>
     * @return int|string
     */
    public function getPromptTokenCount()
    {
        return isset($this->prompt_token_count) ? $this->prompt_token_count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasPromptTokenCount()
    {
        return isset($this->prompt_token_count);
    }

    public function clearPromptTokenCount()
    {
        unset($this->prompt_token_count);
    }

    /**
     * Generated from protobuf field <code>optional int64 prompt_token_count = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPromptTokenCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->prompt_token_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 candidates_token_count = 2;</code>
     * @return int|string
     */
    public function getCandidatesTokenCount()
    {
        return isset($this->candidates_token_count) ? $this->candidates_token_count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasCandidatesTokenCount()
    {
        return isset($this->candidates_token_count);
    }

    public function clearCandidatesTokenCount()
    {
        unset($this->candidates_token_count);
    }

    /**
     * Generated from protobuf field <code>optional int64 candidates_token_count = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCandidatesTokenCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->candidates_token_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 total_token_count = 3;</code>
     * @return int|string
     */
    public function getTotalTokenCount()
    {
        return isset($this->total_token_count) ? $this->total_token_count : GPBUtil::compatibleInt64(0, '0');
    }

    public function hasTotalTokenCount()
    {
        return isset($this->total_token_count);
    }

    public function clearTotalTokenCount()
    {
        unset($this->total_token_count);
    }

    /**
     * Generated from protobuf field <code>optional int64 total_token_count = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTotalTokenCount(int|string $var)
    {
        GPBUtil::checkInt64($var);
        $this->total_token_count = $var;

        return $this;
    }

}

