<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/batch_delete.proto

namespace Weaviate\Client\Proto\GPBMetadata\V1;

class BatchDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Weaviate\Client\Proto\GPBMetadata\V1\Base::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCB\x05\x0A\x15v1/batch_delete.proto\x12\x0Bweaviate.v1\"\xE6\x01\x0A\x12BatchDeleteRequest\x12\x12\x0A\x0Acollection\x18\x01 \x01(\x09\x12%\x0A\x07filters\x18\x02 \x01(\x0B2\x14.weaviate.v1.Filters\x12\x0F\x0A\x07verbose\x18\x03 \x01(\x08\x12\x0F\x0A\x07dry_run\x18\x04 \x01(\x08\x12=\x0A\x11consistency_level\x18\x05 \x01(\x0E2\x1D.weaviate.v1.ConsistencyLevelH\x00\x88\x01\x01\x12\x13\x0A\x06tenant\x18\x06 \x01(\x09H\x01\x88\x01\x01B\x14\x0A\x12_consistency_levelB\x09\x0A\x07_tenant\"\xA4\x01\x0A\x10BatchDeleteReply\x12\x0C\x0A\x04took\x18\x01 \x01(\x02\x12\x0E\x0A\x06failed\x18\x02 \x01(\x03\x12\x0F\x0A\x07matches\x18\x03 \x01(\x03\x12\x12\x0A\x0Asuccessful\x18\x04 \x01(\x03\x12/\x0A\x07objects\x18\x05 \x03(\x0B2\x1E.weaviate.v1.BatchDeleteObject\x12\x12\x0A\x05limit\x18\x06 \x01(\x03H\x00\x88\x01\x01B\x08\x0A\x06_limit\"S\x0A\x11BatchDeleteObject\x12\x0C\x0A\x04uuid\x18\x01 \x01(\x0C\x12\x12\x0A\x0Asuccessful\x18\x02 \x01(\x08\x12\x12\x0A\x05error\x18\x03 \x01(\x09H\x00\x88\x01\x01B\x08\x0A\x06_errorB\xB7\x01\x0A#io.weaviate.client.grpc.protocol.v1B\x18WeaviateProtoBatchDeleteZ4github.com/weaviate/weaviate/grpc/generated;protocol\xCA\x02\x18Weaviate\\Client\\Proto\\V1\xE2\x02\$Weaviate\\Client\\Proto\\GPBMetadata\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

