<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/health_weaviate.proto

namespace Weaviate\Client\Proto\GPBMetadata\V1;

class HealthWeaviate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB2\x03\x0A\x18v1/health_weaviate.proto\x12\x0Bweaviate.v1\"-\x0A\x1AWeaviateHealthCheckRequest\x12\x0F\x0A\x07service\x18\x01 \x01(\x09\"\xA1\x01\x0A\x1BWeaviateHealthCheckResponse\x12F\x0A\x06status\x18\x01 \x01(\x0E26.weaviate.v1.WeaviateHealthCheckResponse.ServingStatus\":\x0A\x0DServingStatus\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x0B\x0A\x07SERVING\x10\x01\x12\x0F\x0A\x0BNOT_SERVING\x10\x02B\xAD\x01\x0A#io.weaviate.client.grpc.protocol.v1B\x0EWeaviateHealthZ4github.com/weaviate/weaviate/grpc/generated;protocol\xCA\x02\x18Weaviate\\Client\\Proto\\V1\xE2\x02\$Weaviate\\Client\\Proto\\GPBMetadata\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

