<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/tenants.proto

namespace Weaviate\Client\Proto\GPBMetadata\V1;

class Tenants
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA7\x07\x0A\x10v1/tenants.proto\x12\x0Bweaviate.v1\"\\\x0A\x11TenantsGetRequest\x12\x12\x0A\x0Acollection\x18\x01 \x01(\x09\x12)\x0A\x05names\x18\x02 \x01(\x0B2\x18.weaviate.v1.TenantNamesH\x00B\x08\x0A\x06params\"\x1D\x0A\x0BTenantNames\x12\x0E\x0A\x06values\x18\x01 \x03(\x09\"E\x0A\x0FTenantsGetReply\x12\x0C\x0A\x04took\x18\x01 \x01(\x02\x12\$\x0A\x07tenants\x18\x02 \x03(\x0B2\x13.weaviate.v1.Tenant\"R\x0A\x06Tenant\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12:\x0A\x0Factivity_status\x18\x02 \x01(\x0E2!.weaviate.v1.TenantActivityStatus*\xAF\x03\x0A\x14TenantActivityStatus\x12&\x0A\"TENANT_ACTIVITY_STATUS_UNSPECIFIED\x10\x00\x12\x1E\x0A\x1ATENANT_ACTIVITY_STATUS_HOT\x10\x01\x12\x1F\x0A\x1BTENANT_ACTIVITY_STATUS_COLD\x10\x02\x12!\x0A\x1DTENANT_ACTIVITY_STATUS_FROZEN\x10\x04\x12%\x0A!TENANT_ACTIVITY_STATUS_UNFREEZING\x10\x05\x12#\x0A\x1FTENANT_ACTIVITY_STATUS_FREEZING\x10\x06\x12!\x0A\x1DTENANT_ACTIVITY_STATUS_ACTIVE\x10\x07\x12#\x0A\x1FTENANT_ACTIVITY_STATUS_INACTIVE\x10\x08\x12\$\x0A TENANT_ACTIVITY_STATUS_OFFLOADED\x10\x09\x12%\x0A!TENANT_ACTIVITY_STATUS_OFFLOADING\x10\x0A\x12\$\x0A TENANT_ACTIVITY_STATUS_ONLOADING\x10\x0B\"\x04\x08\x03\x10\x03B\xB3\x01\x0A#io.weaviate.client.grpc.protocol.v1B\x14WeaviateProtoTenantsZ4github.com/weaviate/weaviate/grpc/generated;protocol\xCA\x02\x18Weaviate\\Client\\Proto\\V1\xE2\x02\$Weaviate\\Client\\Proto\\GPBMetadata\\V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

